services:
    _defaults:
        autowire: false
        public: true
        autoconfigure: false

    # Agenda tool settings
    chamilo_course.settings.agenda:
        class: Chamilo\CourseBundle\Settings\AgendaCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.agenda, namespace: agenda}

    # Announcement tool settings
    chamilo_course.settings.announcement:
        class: Chamilo\CourseBundle\Settings\AnnouncementCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.announcement, namespace: announcement}

    # Course settings
    chamilo_course.settings.assignment:
        class: Chamilo\CourseBundle\Settings\AssignmentCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.assignment, namespace: assignment}

    # Course settings
    chamilo_course.settings.attendance:
        class: Chamilo\CourseBundle\Settings\AttendanceCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.attendance, namespace: attendance}

    # Course settings
    chamilo_course.settings.blog:
        class: Chamilo\CourseBundle\Settings\BlogCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.blog, namespace: blog}

    # Course settings
    chamilo_course.settings.course_description:
        class: Chamilo\CourseBundle\Settings\CourseDescriptionCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.course_description, namespace: course_description}

    # Course settings
    chamilo_course.settings.chat:
        class: Chamilo\CourseBundle\Settings\ChatCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.chat, namespace: chat}

    # Course settings
    chamilo_course.settings.course_progress:
        class: Chamilo\CourseBundle\Settings\CourseProgressCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.course_progress, namespace: course_progress}

    # Course settings
    chamilo_course.settings.document:
        class: Chamilo\CourseBundle\Settings\DocumentCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.document, namespace: document}

    # Course settings
    chamilo_course.settings.dropbox:
        class: Chamilo\CourseBundle\Settings\DropboxCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.dropbox, namespace: dropbox}

    # Course settings
    chamilo_course.settings.exercise:
        class: Chamilo\CourseBundle\Settings\ExerciseCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.quiz, namespace: quiz}

    # Course settings
    chamilo_course.settings.forum:
        class: Chamilo\CourseBundle\Settings\ForumCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.forum, namespace: forum}

    # Course settings
    chamilo_course.settings.glossary:
        class: Chamilo\CourseBundle\Settings\GlossaryCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.glossary, namespace: glossary}

   # Course settings
    chamilo_course.settings.gradebook:
        class: Chamilo\CourseBundle\Settings\GradebookCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.gradebook, namespace: gradebook}

    # Course settings
    chamilo_course.settings.group:
        class: Chamilo\CourseBundle\Settings\GroupCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.group, namespace: group}

    # Course settings
    chamilo_course.settings.learning_path:
        class: Chamilo\CourseBundle\Settings\LearningPathCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.learnpath, namespace: learnpath}

    chamilo_course.settings.link:
        class: Chamilo\CourseBundle\Settings\LinkCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.link, namespace: link}

    # Maintenance
    chamilo_course.settings.maintenance:
        class: Chamilo\CourseBundle\Settings\MaintenanceCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.maintenance, namespace: maintenance}

    # Notebook
    chamilo_course.settings.notebook:
        class: Chamilo\CourseBundle\Settings\NotebookCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.notebook, namespace: notebook}

    # Course settings
    chamilo_course.settings.settings:
        class: Chamilo\CourseBundle\Settings\SettingsCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.settings, namespace: settings}

    chamilo_course.settings.survey:
        class: Chamilo\CourseBundle\Settings\SurveyCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.survey, namespace: survey}

    chamilo_course.settings.tracking:
        class: Chamilo\CourseBundle\Settings\TrackingCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.tracking, namespace: tracking}

    chamilo_course.settings.user:
        class: Chamilo\CourseBundle\Settings\UserCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.user, namespace: user}

    chamilo_course.settings.wiki:
        class: Chamilo\CourseBundle\Settings\WikiCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.wiki, namespace: wiki}
