knpu_oauth2_client:
    clients:
        generic:
            type: generic
            provider_class: League\OAuth2\Client\Provider\GenericProvider
            client_id: ''
            client_secret: ''
            provider_options:
                responseResourceOwnerId: 'sub'
                scopes:
                    - openid
            redirect_route: chamilo.oauth2_generic_check

        facebook:
            type: facebook
            client_id: ''
            client_secret: ''
            redirect_route: chamilo.oauth2_facebook_check
            graph_api_version: 'v20.0'

        keycloak:
            type: keycloak
            client_id: ''
            client_secret: ''
            redirect_route: chamilo.oauth2_keycloak_check
            auth_server_url: null
            realm: null

        azure:
            type: azure
            client_id: ''
            redirect_route: chamilo.oauth2_azure_check
            client_secret: ' '

        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
