framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'

when@dev:
    framework:
        mailer:
            dsn: '%env(MAILER_DSN)%'

when@test:
    framework:
        mailer:
            dsn: 'null://null'
