<?php
// Chamilo version {NEW_VERSION}
// File generated by /install/index.php script - {DATE_GENERATED}
/* For licensing terms, see /license.txt */
/**
 *		Chamilo configuration
 *
 * This file contains a list of variables that can be modified by the campus
 * site's server administrator. Pay attention when changing these variables,
 * some changes may cause Chamilo to stop working.
 * If you changed some settings and want to restore them, please have a look at
 * configuration.dist.php. That file is an exact copy of the config file at
 * install time.
 */

/**
 * $_configuration define only the bare essential variables
 * for configuring the platform (paths, database connections, ...).
 * Changing a $_configuration variable CAN generally break the installation.
 * Besides the $_configuration, a $_settings array also exists, that
 * contains variables that can be changed and will not break the platform.
 * These optional settings are defined in the database, now
 * (table settings_current).
 */

/**
 * MYSQL connection settings
 */
// Your MySQL server
$_configuration['db_host']     = 'localhost';
// Your MySQL username
$_configuration['db_user']     = 'root';
// Your MySQL password
$_configuration['db_password'] = 'root';

/**
 * Database settings
 */
// Prefix for course tables (IF NOT EMPTY, can be replaced by another prefix, else leave empty)
$_configuration['table_prefix']          = '';
// Separator between database and table name (DO NOT MODIFY THIS)
$_configuration['db_glue']               = '`.`';
// prefix all created bases (for courses) with this string
$_configuration['db_prefix']             = '';
// main Chamilo database
$_configuration['main_database']         = 'chamilo';

/**
 * Directory settings
 */
// URL to the root of your Chamilo installation, e.g.: http://www.mychamilo.com/
$_configuration['root_web']       = 'http://localhost/chamilo';

/**
 *
/**
 * Misc. settings
 */
// Security word for password recovery
$_configuration['security_key']      = md5(uniqid(rand().time()));
// Hash function method
$_configuration['password_encryption']      = 'sha1';
// You may have to restart your web server if you change this
$_configuration['session_stored_in_db']     = false;
// Session lifetime
$_configuration['session_lifetime']  = 3600;
// Activation for multi-url access
//$_configuration['multiple_access_urls']					= true;
//Deny the elimination of users
$_configuration['deny_delete_users'] = false;
// Version settings
$_configuration['system_version']    = '1.10';