version: "2"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: true
    config:
      threshold: 20
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    config:
      threshold: 20
  return-statements:
    enabled: false

plugins:
  phan:
    enabled: false
    config:
      file_extensions: "php"

  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG

  phpcodesniffer:
    enabled: true
    config:
      standard: "Symfony2"
      file_extensions: "php"
    checks:
      PSR1 Classes ClassDeclaration MissingNamespace:
        enabled: false
      PSR1 Files SideEffects FoundWithSymbols:
        enabled: false
      Squiz Strings ConcatenationSpacing PaddingFound:
        enabled: false
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "codesize.xml"

  sonar-php:
    enabled: false
    checks:
      php:S1192:
        enabled: false

  duplication:
    enabled: false

exclude_patterns:
- cli-config.php
- app/cache/
- app/logs/
- app/config/
- app/SymfonyRequirements.php
- app/Migrations/
- app/Resources/
- main/admin/db.php
- main/admin/ldap_synchro.php
- main/auth/cas/lib/
- main/auth/shibboleth
- main/auth/openid
- main/chat/emoji_strategy.php
- main/default_course_document
- main/document/Wami.swf
- main/fonts/
- main/inc/ajax/Wami.swf
- main/inc/lib/browser/
- main/inc/lib/freemindflashbrowser/
- main/inc/lib/internationalization_database/
- main/inc/lib/javascript/
- main/inc/lib/kses-0.2.2/
- main/inc/lib/mimetex/
- main/inc/lib/nanogong/
- main/inc/lib/nusoap/
- main/inc/lib/opengraph/*
- main/inc/lib/ppt2png/
- main/inc/lib/phpseclib
- main/inc/lib/pear/
- main/inc/lib/phpmailer/
- main/inc/lib/phpseclib/
- main/inc/lib/svg-edit/
- main/inc/lib/swfobject/
- main/inc/lib/mediaplayer
- main/inc/lib/mxgraph/
- main/inc/lib/wami-recorder/
- main/inc/lib/xajax/
- main/lp/packaging/
- main/template/
- main/img/
- main/lang/
- plugin/buycourses/resources/js/
- plugin/buycourses/src/Culqi/
- plugin/buycourses/src/Requests/
- plugin/buycourses/src/Requests.php
- plugin/buycourses/src/paypalfunctions.php
- plugin/vchamilo/cli/
- plugin/kannelsms/vendor/
- plugin/clockworksms/vendor/
- plugin/tour/intro.js
- plugin/pens/lib
- plugin/bbb/lib/bbb_api.php
- plugin/ims_lti/OAuthSimple.php
- plugin/sepe/src/wsse/
- plugin/test2pdf/class/
- plugin/jcapture/lib/
- plugin/jcapture/src/
- tests/
- vendor/
- web/
