build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
    tests:
        override:
            command: "php -v"
    dependencies:
        override:
            - "php -v"

checks:
    php: true

filter:
    excluded_paths:
        - 'assets/*'
        - 'bin/*'
        - 'config/*'
        - 'documentation/*'
        - 'public/main/admin/db.php'
        - 'public/main/admin/ldap_synchro.php'
        - 'public/main/chat/emoji_strategy.php'
        - 'public/main/inc/lib/javascript/*'
        - 'public/main/inc/lib/kses-0.2.2/*'
        - 'public/main/inc/lib/mimetex/*'
        - 'public/main/inc/lib/nusoap/*'
        - 'public/main/inc/lib/opengraph/*'
        - 'public/main/inc/lib/ppt2png/*'
        - 'public/main/inc/lib/pear/*'
        - 'public/main/inc/lib/xajax/*'
        - 'public/main/lp/packaging/*'
        - 'public/main/template/*'
        - 'public/main/lang/*'
        - 'public/plugin/buycourses/src/Culqi/*'
        - 'public/plugin/buycourses/src/Requests/*'
        - 'public/plugin/buycourses/src/paypalfunctions.php'
        - 'public/plugin/buycourses/src/Requests.php'
        - 'public/plugin/vchamilo/cli/*'
        - 'public/plugin/pens/lib/'
        - 'public/plugin/bbb/lib/bbb_api.php'
        - 'public/plugin/ims_lti/OAuthSimple.php'
        - 'public/plugin/sepe/src/wsse/*'
        - 'public/plugin/test2pdf/class/*'
        - 'public/plugin/jcapture/lib/*'
        - 'public/plugin/jcapture/src/*'
        - 'tests/*'
        - 'var/cache/*'
        - 'var/log/*'
        - 'vendor/*'
        - 'public/libs/*'
        - 'public/img/*'
