ignore:
  - "src/Kernel.php"
  - "src/CoreBundle/DependencyInjection"
  - "src/CoreBundle/Component/Editor"
  - "src/CoreBundle/Component/HTMLPurifier"
  - "src/CoreBundle/Utils/ChamiloUtil.php"
  - "src/CoreBundle/Component/Utils/ScriptHandler.php"
  - "src/CoreBundle/Framework/Container.php"
  - "src/CoreBundle/ChamiloCoreBundle.php"
  - "src/CourseBundle/ChamiloCourseBundle.php"
  - "src/CourseBundle/DependencyInjection"
  - "src/CourseBundle/Component"
  - "src/LtiBundle"
