<?php
/*
for more information: see languages.txt in the lang folder.
*/
$ClearContent = "دوکئوسیک محیط آموزشیمجازی است کهبه اساتید ومربیان اجازهمی دهد تا بهآسانی به آفرینشدروس مجازیبپردازند وپیشرفت دانشجویانو کار آموزانخود را اندازهبگیرند. اینمحیط همچنینبه دانشجویاناجازه می دهدتا پیرامونمحتوای درسیبه همکاری فعالبپردازند<br><p><b>Teacher</b></p> <p>Dokeos is a Learning and Knowledge Management System. It allows the teacher to organise learning materials, learning paths and to manage the interaction with his/her students. All this is made inside the web browser.</p> <p>To use Chamilo as a teacher, you need a login and a password. Depending on the security settings of your portal, you an get these by self-registration (right hand menu) or from the central administration of your organisation. Note that a login and a password never contain spaces or acents and that they are case sensitive. Type your login/password, then create a course (top right) or use the course that has been created for you by the central administration of your organisation.</p> <p>To add a colleague as co-administrator of your course: <ol><li>If he/she is not yet registered in the system, register him/her and select 'Teacher' as a profile,</li> <li>If he/she is already registered in the system, temporarily open course subscription in Course settings and ask him/her to enroll in your course. Then edit his/her profile and give him/her Teacher rights.</li></ol></p> <p> Every Chamilo tool contains a contextual help represented by a red buoy. If you don't find there the good information, consider checking the Chamilo documentation page: <a href=\"http://www.chamilo.org/documentation.php\">http://www.chamilo.org/documentation.php</a> and download the teacher manual. in your own language or in English</p> <p><b>Student</b></p> <p>This portal allows you to follow and participate to courses, trainings, collaborative workshops etc. It has been created to promote active learning: project-based, problem-based, casesbased learning, collaborative research etc. Your teachers have build learning areas that can present as simple documents folders or sophisticated self-learning or group learning sequences of activities.</p> <p>Registration process can vary from one organisation to the other. In some cases, self-registration is allowed. In others, you should get from the central administration a login and a password.</p>";
$WCAGImage = "تصویر";
$WCAGLabel = "عنوان تصویر";
$WCAGLink = "پیوند";
$WCAGLinkLabel = "عنوان پیوند";
$ErrorNoLabel = "&#1575;&#1740;&#1606; &#1578;&#1589;&#1608;&#1740;&#1585; &#1593;&#1606;&#1608;&#1575;&#1606; &#1711;&#1584;&#1575;&#1585;&#1740; &#1606;&#1588;&#1583;&#1607; &#1575;&#1587;&#1578;";
$AllLanguages = "تمامی زبان ها";
$WCAGEditor = "(WCAG Editor) ادیتور دبلیوسی ای جی";
$WCAGGoMenu = "رفتن به فهرست";
$WCAGGoContent = "رفتن به متن";
?>