<?php /*
for more information: see languages.txt in the lang folder. 
*/
$langHFor = "Fórum - pomoc";
$langForContent = "Fórum je písaný a asynchrónny diskusný nástroj. Tam kde email umožní rozhovor jeden na jedného, fóra umožnia verejné alebo skoro verejné (skupinové) rozhovory.</p><p>Technicky povedané, používatelia potrebujú na využívanie Dokeos fór len internetový prehliada&#269;.</P><p>Na zorganizovanie fór kliknite na \'Administrácia fóra\'. Diskusie sú usporiadané v skupinách a podskupinách nasledovne:</p><p><b>Kategória > Fórum > Téma > Odpovede</b></p>Pre usporiadanie diskusií Vašich používate&#318;ov je nevyhnutné vopred usporiada&#357; kategórie a fóra a na nich ponecha&#357; vytvorenie tém a odpovedí. Štandardne obsahuje Dokeos fórum len kategóriu \'Verejné\', príklad fóra a príklad témy.</p><p>Prvá vec, ktorú by ste mali spravi&#357; je zmaza&#357; príklad témy a zmeni&#357; názov prvého fóra. Následne môžete v kategórii \'verejné\' vytvori&#357; iné fóra, o témach, ktoré budú vyhovova&#357; scenáru Vášho vyu&#269;ovania.</p><p>Nemiešajte kategórie a fóra a nezabudnite, že prázdna kategória (bez fór) sa neobjaví študentskom poh&#318;ade.</p><p>Popisom fóra môže by&#357; zoznam jeho &#269;lenov, definícia cie&#318;a, úlohy, témy...</p> <p>Skupinové fóra by nemali by&#357; vytvorené prostredníctvom nástroja \'Fórum\' ale cez nástroj \'Skupiny\'. Tak budete môc&#357; rozhodnú&#357;, &#269;i budú skupinové fóra súkromné alebo verejné.</p> <b>Pedagogické tipy</b> <p>Niektorí lektori/inštruktori používajú fóra na posielanie opráv (korektúr). Študent uverejní prácu. Lektor ju opraví stla&#269;ením tla&#269;idla upravi&#357; (žltá ceruzka) a pomocou WYSYWIG editora (používa napríklad farby a pod&#269;iarknutia). Takto môžu aj iní študenti zisti&#357;, &#269;o je nesprávne a treba to opravi&#357;.";
$langHDropbox = "Schránka na dokumenty";
$langDropboxContent = "<p>Schránka na dokumenty je nástroj na správu obsahu ur&#269;ený na výmenu informácií medzi používate&#318;mi. Akýko&#318;vek typ súboru je akceptovaný: Word, Excel, PDF, at&#271;... Schránka na dokumenty bude spravova&#357; verzie tak, aby zabránila zni&#269;eniu dokumentu iným dokumentom s rovnakým názvom.</p> <p>Schránka na dokumenty zobrazuje súbory, ktoré Vám boli poslané (prie&#269;inok prijaté) a súbory, ktoré ste poslali iným &#269;lenom tohto kurzu (prie&#269;inok poslané). </p><p>Ak sa zoznam prijatých alebo poslaných súborov stane príliš dlhým, môžete zmaza&#357; všetky alebo len niektoré súbory zo zoznamu. Súbor ako taký nebude odstránený, pokým ho bude vo svojom zozname vidie&#357; druhá strana.</p> <p>Ak chcete posla&#357; dokument viac ako jednej osobe, musíte použi&#357; CTRL+klik vo výberovom okne.  Výberové okno je pole formulára zobrazujúce zoznam &#269;lenov.</p>";
$langHHome = "Domovská stránka kurzu - pomoc ";
$langHomeContent = "<p>Domovská stránka kurzu ponúka sadu nástrojov: úvodný text, popis kurzu, správca dokumentov, at&#271;... Táto stránka je modulová: jedným klikom môžete skry&#357; / ukáza&#357; akýko&#318;vek nástroj. Skryté nástroje môžu by&#357; kedyko&#318;vek znovu aktivované.</p> <b>Navigácia</b> <p>Na prehliadanie Vášho kurzu máte dva naviga&#269;né nástroje. Jeden v&#318;avo hore – strom, ktorý Vám ukáže, kde a ako hlboko v kurze sa nachádzate. Vpravo hore sa môžete k nástroju dosta&#357; klikom na jeho ikonu. Bez oh&#318;adu nato, &#269;i vyberiete kód Vášho kurzu v&#318;avo (vždy použite VE&#317;KÉ PÍSMENÁ) alebo kliknete na ikonu dom&#269;eka vpravo, dostanete sa na domovskú stránku Vášho kurzu.</p> <b>Osved&#269;ené postupy</b> <p>Pre motiváciu Vašich študentov je dôležité, aby priestor kurzu bol dynamickým priestorom. To bude nazna&#269;ova&#357;, že \'za obrazovkou\' niekto je. Rýchla cesta, ako to dosiahnu&#357; je úprava úvodného textu (klik na žltú ceruzku) aspo&#328; raz za týžde&#328;. Môžete tak informova&#357; o posledných novinkách, blížiacich sa uzávierkach at&#271;.</p> <p>Pre postavenie Vášho kurzu by mohlo by&#357; podstatné nasledovanie týchto etáp:<ol><li>V nastaveniach kurzu skontrolujte Prístup na kurz: Súkromný a Prihlásenie: Zakázané. Takto po&#269;as tvorby kurzu nebude môc&#357; nikto vstúpi&#357; do priestoru kurzu,</li> <li>Zobrazte všetky nástroje klikom na šedý odkaz na spodku stránky,</li> <li>Pre vyplnenie Vášho priestoru obsahom, udalos&#357;ami, postupmi, testami... použite všetky dostupné nástroje,</li> <li>Skryte všetky nástroje: Vaša domovská stránka bude prázdna pri poh&#318;ade študenta,</li> <li>Použite Osnovu na skonštruovanie procesu, pod&#318;a ktorého by sa mali študenti u&#269;i&#357;. Takto použijete iné nástroje, ale neukážete ich na prvý poh&#318;ad,</li> <li>Kliknite na ikonu oka ved&#318;a osnovy, ktorú ste vytvorili. Táto osnova sa potom zobrazí na Vašej domovskej stránke,</li> <li>Príprava priestoru pre Váš kurz je skon&#269;ená. Vaša domovská stránka zobrazí úvodný text nasledovaný len jedným odkazom a tento odkaz prevedie študentov kurzom. Aby ste veci videli z poh&#318;adu študenta, kliknite na možnos&#357; Poh&#318;ad študenta (vpravo hore).<I></I></li></ol>";
$langHClar = "Dokeos - pomoc";
$langHDoc = "Dokumenty - pomoc";
$langHUser = "Používatelia - pomoc";
$langHExercise = "Testy - pomoc";
$langHPath = "Pomoc k osnove";
$langHDescription = "Popis kurzu - pomoc";
$langDescriptionContent = "<p>Tento nástroj Vám pomôže pri opise Vášho kurzu vecne a triezvo. To môže pomôc&#357; Vašim budúcim študentom získa&#357; jasný obraz o tom, &#269;o môžu od kurzu o&#269;akáva&#357;. Je to tiež príležitos&#357; na opätovné zamyslenie sa nad scenárom kurzu.</p>Položky sú zadané len ako návrhy. Ak chcete vytvori&#357; popis kurzu s Vašimi vlastnými položkami, použite len položku \'Iné\' a zada&#357; jej vlastný názov.</p> <p> Pre vyplnenie popisu kurzu vyberte možnos&#357; \'Vytvori&#357;\' > otvorte rolovaciu ponuku a vyberte požadovanú položku > vypl&#328;te formulár > Potvr&#271;te. Vždy môžete upravi&#357; alebo zmaza&#357; obsah každej položky klikom na ceruzku alebo &#269;ervený krížik.</p>";
$langLinksContent = "<p>Nástroj Odkazy Vám umož&#328;uje vytvori&#357; knižnicu zdrojom pre študentov. Najmä zdrojov, ktoré ste nevytvorili vy samy. </p> <p>Ke&#271; bude zoznam dlhý, môže by&#357; dobré usporiada&#357; odkazy do kategórií, aby študenti &#318;ahko našli potrebné informácie na správnom mieste. Môžete upravi&#357; každý odkaz a tak ho preradi&#357; do  novej kategórie (najskôr musíte kategóriu vytvori&#357;).</p> <p>Prostredníctvom popisného po&#318;a môžete poskytnú&#357; prvotné informácie o cie&#318;ových web stránkach ale tiež na opísanie toho, ako by mali študenti s odkazmi pracova&#357;. Ak napríklad odkážete na web stránku o Aristotelovi, v popisnom poli môžete požiada&#357; študentov aby si naštudovali rozdiel medzi syntézou a analýzou.";
$langMycoursesContent = "<p>Ke&#271; sa prihlásite do platformy, budete na Vašej <i>osobnej úvodnej stránke</i>.</p> <p> V hlavnej oblasti (stred) vidíte v položke \"<b>Môj zoznam kurzov</b>\" zoznam všetkých Vašich kurzov. V závislosti od Vašich používate&#318;ských práv môžete ma&#357; tiež možnos&#357; vytvori&#357; nové kurzy (cez menu po pravej ruke).</p> <p>V hornom banneri vidíte<ul><li>\"<b>Moje e-portfólio</b>\": použite túto možnos&#357; na zmenu hesla, používate&#318;ského mena, obrázku alebo iných nastavení. Tiež môžete skontrolova&#357; Vašu osobnú štatistiku platformy;</li> <li>\"<b>Moja agenda</b>\": obsahuje všetky udalosti agendy kurzov, v ktorých ste zaregistrovaný.</li></ul> </p> <p> <b>Upravi&#357; môj zoznam kurzov</b>, v menu po pravej ruke Vám umož&#328;uje zapísa&#357; sa do nových kurzov pokia&#318; lektor alebo organizácia ponechala kurzy otvorené pre zapísanie sa. Tento odkaz Vám tiež umožní odhlásenie sa z kurzov.</p> <p> Odkazy <b>Podporné Fórum</b> a <b>Dokumentácia</b> odkazujú na hlavnú webovú stránku Dokeos, kde môžete položi&#357; technické a pedagogické otázky a nájs&#357; viac informácií.</li> Pre vstup do kurzu (hlavný priestor Vašej úvodnej stránky), kliknite na jeho názov. Váš profil môže by&#357; pre každý kurz rozdielny. Môžete by&#357; teda v jednom kurze lektorom a v &#271;alšom študentom. </p>";
$langHAgenda = "Agenda - pomoc";
$langHAnnouncements = "Pomocné oznamy";
$langHChat = "Pokec - Pomoc";
$langHWork = "Zadania - pomoc";
$langHSettings = "Nastavenia kurzu - pomoc";
$langHExternal = "Prida&#357; odkaz - pomoc";
$langClarContent3 = "Vymaza&#357; obsah ";
$langClarContent4 = "Vymaza&#357; obsah ";
$langClarContent1 = "Vymaza&#357; obsah ";
$langClarContent2 = "Vymaza&#357; obsah ";
$langHGroups = "Skupiny";
$HSurvey = "Prieskum - pomoc";
?>