<?php /*
for more information: see languages.txt in the lang folder. 
*/
$langHFor = "Fórum - pomoc";
$langForContent = "Fórum je písaný a asynchrónny diskusný nástroj. Tam kde email umožní rozhovor jeden na jedného, fóra umožnia verejné alebo skoro verejné (skupinové) rozhovory.</p><p>Technicky povedané, používatelia potrebujú na využívanie Dokeos fór len internetový prehliada&#269;.</P><p>Na zorganizovanie fór kliknite na \'Administrácia fóra\'. Diskusie sú usporiadané v skupinách a podskupinách nasledovne:</p><p><b>Kategória > Fórum > Téma > Odpovede</b></p>Pre usporiadanie diskusií Vašich používate&#318;ov je nevyhnutné vopred usporiada&#357; kategórie a fóra a na nich ponecha&#357; vytvorenie tém a odpovedí. Štandardne obsahuje Dokeos fórum len kategóriu \'Verejné\', príklad fóra a príklad témy.</p><p>Prvá vec, ktorú by ste mali spravi&#357; je zmaza&#357; príklad témy a zmeni&#357; názov prvého fóra. Následne môžete v kategórii \'verejné\' vytvori&#357; iné fóra, o témach, ktoré budú vyhovova&#357; scenáru Vášho vyu&#269;ovania.</p><p>Nemiešajte kategórie a fóra a nezabudnite, že prázdna kategória (bez fór) sa neobjaví študentskom poh&#318;ade.</p><p>Popisom fóra môže by&#357; zoznam jeho &#269;lenov, definícia cie&#318;a, úlohy, témy...</p> <p>Skupinové fóra by nemali by&#357; vytvorené prostredníctvom nástroja \'Fórum\' ale cez nástroj \'Skupiny\'. Tak budete môc&#357; rozhodnú&#357;, &#269;i budú skupinové fóra súkromné alebo verejné.</p> <b>Pedagogické tipy</b> <p>Niektorí lektori/inštruktori používajú fóra na posielanie opráv (korektúr). Študent uverejní prácu. Lektor ju opraví stla&#269;ením tla&#269;idla upravi&#357; (žltá ceruzka) a pomocou WYSYWIG editora (používa napríklad farby a pod&#269;iarknutia). Takto môžu aj iní študenti zisti&#357;, &#269;o je nesprávne a treba to opravi&#357;.";
$langHDropbox = "Schránka na dokumenty";
$langDropboxContent = "<p>Schránka na dokumenty je nástroj na správu obsahu ur&#269;ený na výmenu informácií medzi používate&#318;mi. Akýko&#318;vek typ súboru je akceptovaný: Word, Excel, PDF, at&#271;... Schránka na dokumenty bude spravova&#357; verzie tak, aby zabránila zni&#269;eniu dokumentu iným dokumentom s rovnakým názvom.</p> <p>Schránka na dokumenty zobrazuje súbory, ktoré Vám boli poslané (prie&#269;inok prijaté) a súbory, ktoré ste poslali iným &#269;lenom tohto kurzu (prie&#269;inok poslané). </p><p>Ak sa zoznam prijatých alebo poslaných súborov stane príliš dlhým, môžete zmaza&#357; všetky alebo len niektoré súbory zo zoznamu. Súbor ako taký nebude odstránený, pokým ho bude vo svojom zozname vidie&#357; druhá strana.</p> <p>Ak chcete posla&#357; dokument viac ako jednej osobe, musíte použi&#357; CTRL+klik vo výberovom okne.  Výberové okno je pole formulára zobrazujúce zoznam &#269;lenov.</p>";
$langHHome = "Domovská stránka kurzu - pomoc ";
$langHomeContent = "<p>Domovská stránka kurzu ponúka sadu nástrojov: úvodný text, popis kurzu, správca dokumentov, at&#271;... Táto stránka je modulová: jedným klikom môžete skry&#357; / ukáza&#357; akýko&#318;vek nástroj. Skryté nástroje môžu by&#357; kedyko&#318;vek znovu aktivované.</p> <b>Navigácia</b> <p>Na prehliadanie Vášho kurzu máte dva naviga&#269;né nástroje. Jeden v&#318;avo hore – strom, ktorý Vám ukáže, kde a ako hlboko v kurze sa nachádzate. Vpravo hore sa môžete k nástroju dosta&#357; klikom na jeho ikonu. Bez oh&#318;adu nato, &#269;i vyberiete kód Vášho kurzu v&#318;avo (vždy použite VE&#317;KÉ PÍSMENÁ) alebo kliknete na ikonu dom&#269;eka vpravo, dostanete sa na domovskú stránku Vášho kurzu.</p> <b>Osved&#269;ené postupy</b> <p>Pre motiváciu Vašich študentov je dôležité, aby priestor kurzu bol dynamickým priestorom. To bude nazna&#269;ova&#357;, že \'za obrazovkou\' niekto je. Rýchla cesta, ako to dosiahnu&#357; je úprava úvodného textu (klik na žltú ceruzku) aspo&#328; raz za týžde&#328;. Môžete tak informova&#357; o posledných novinkách, blížiacich sa uzávierkach at&#271;.</p> <p>Pre postavenie Vášho kurzu by mohlo by&#357; podstatné nasledovanie týchto etáp:<ol><li>V nastaveniach kurzu skontrolujte Prístup na kurz: Súkromný a Prihlásenie: Zakázané. Takto po&#269;as tvorby kurzu nebude môc&#357; nikto vstúpi&#357; do priestoru kurzu,</li> <li>Zobrazte všetky nástroje klikom na šedý odkaz na spodku stránky,</li> <li>Pre vyplnenie Vášho priestoru obsahom, udalos&#357;ami, postupmi, testami... použite všetky dostupné nástroje,</li> <li>Skryte všetky nástroje: Vaša domovská stránka bude prázdna pri poh&#318;ade študenta,</li> <li>Použite Osnovu na skonštruovanie procesu, pod&#318;a ktorého by sa mali študenti u&#269;i&#357;. Takto použijete iné nástroje, ale neukážete ich na prvý poh&#318;ad,</li> <li>Kliknite na ikonu oka ved&#318;a osnovy, ktorú ste vytvorili. Táto osnova sa potom zobrazí na Vašej domovskej stránke,</li> <li>Príprava priestoru pre Váš kurz je skon&#269;ená. Vaša domovská stránka zobrazí úvodný text nasledovaný len jedným odkazom a tento odkaz prevedie študentov kurzom. Aby ste veci videli z poh&#318;adu študenta, kliknite na možnos&#357; Poh&#318;ad študenta (vpravo hore).<I></I></li></ol>";
$langHClar = "Dokeos - pomoc";
$langHDoc = "Dokumenty - pomoc";
$langHUser = "Používatelia - pomoc";
$langHExercise = "Testy - pomoc";
$langHPath = "Pomoc k osnove";
$langHDescription = "Popis kurzu - pomoc";
$langHAgenda = "Agenda - pomoc";
$langHAnnouncements = "Pomocné oznamy";
$langHChat = "Pokec - Pomoc";
$langHWork = "Zadania - pomoc";
$langHSettings = "Nastavenia kurzu - pomoc";
$langHExternal = "Prida&#357; odkaz - pomoc";
$langClarContent3 = "Vymaza&#357; obsah ";
$langClarContent4 = "Vymaza&#357; obsah ";
$langClarContent1 = "Vymaza&#357; obsah ";
$langClarContent2 = "Vymaza&#357; obsah ";
$langHGroups = "Skupiny";
$HSurvey = "Prieskum - pomoc";
?>