<?php
/*
for more information: see languages.txt in the lang folder.
*/
$ClearContent = "<p><b>Instrutor</b></p><p>O Chamilo é uma plataforma/sistema de Gestão do Conhecimento e da Aprendizagem. Permite a um instrutor organizar e gerir cursos, materiais didáticos e interagir com os utilizadores. Toda esta getão é realizada através num ambiente de janela de navegação/browser.p><p>Para gerir o Chamilo como instrutor, necessita de obter um login e uma senha/password. Dependendo das configurações de segurança do seu portal, poderá consegui-los através de um auto-registo (menu do lado direito) ou através do administrador da plataforma/sistema. Tenha em atenção que o login e a senha/password não podem nunca conter espaços ou acentos e que são sensíveis/case sensitive. Introduza o seu login e a sua senha/password e, em seguida, crie um curso (menu superior direito) ou utilize um curso que tenha sido já criado para si pelo administrador da plataforma/sistema.</p><p>Para adicionar um outro utilizador com um perfil de co-administrador ao seu curso:<ol><li>Se ainda não estiver registado na plataforma/sistema, crie o registo e seleccione a opção 'Instrutor' como perfil;</li><li>Se já estiver registado(a) na plataforma/sistema, abra temporáriamente a área de inscrição no curso nas configurações do Curso e solicite-lhe para se inscrever neste. Poderá então editar o seu perfil e atribuir-lhe as permissões de instrutor.</li></ol></p><p>Todas as ferramentas do Chamilo possuem uma ajuda contextual representada por um ícone com a imagem de uma bóia vermelha. Se não encontrar nessa ajuda as informações que necessita, verifique a página de documentação sobre o Chamilo em: <a href=\"http://www.chamilo.org/documentation.php\">http://www.chamilo.org/documentation.php</a> e realize o download do manual do instrutor no seu idioma ou em inglês</p><p><b>Formando</b></p><p>Este portal permite acompanhar e participar em cursos, seminários, workshops/reuniões de colaboração, etc. Foi criado para promover a aprendizagem activa: baseada em projectos, baseada em problemas, baseada em casos de aprendizagem, pesquisa e trabalho colaborativo, etc.Foram criadas áreas de aprendizagem que se podem apresentar através de simples documentos ou sofisticadas pastas com conteúdos de auto-aprendizagem, ou ainda, através de sequências de actividades em grupo.</p><p>O processo de inscrição pode variar de organização para organização. Em alguns casos, a auto-inscrição é permitida. Em outros, deverá solicitar à administração da plataforma/sistema um login e uma senha/password.</p>";
$WCAGImage = "Imagem";
$WCAGLabel = "Identificação/legenda da imagem";
$WCAGLink = "Ligação/link";
$WCAGLinkLabel = "Identificação/legenda da ligação";
$ErrorNoLabel = "Imagem sem legenda/identificação.";
$AllLanguages = "todos os idiomas";
$WCAGEditor = "Editor WCAG";
$WCAGGoMenu = "Ir para o menu";
$WCAGGoContent = "Ir para os conteúdos";
?>