<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-02-17 at 00:38:50.
 */
class AccessurleditsessionstourlTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Accessurleditsessionstourl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        ob_start();
        require_once dirname(__FILE__).'/../../../main/inc/lib/access_url_edit_sessions_to_url_functions.lib.php';
        require_once dirname(__FILE__).'/../../../main/inc/lib/main_api.lib.php';
        $this->object = new Accessurleditsessionstourl;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        ob_end_clean();
    }

    /**
     * Generated from @assert () === false.
     *
     * @covers Accessurleditsessionstourl::search_sessions
     */
    public function testSearch_sessions()
    {
        ob_start();
        $this->assertSame(
          false,
          $this->object->search_sessions(null,null)
        );
        ob_end_clean();
    }
}
