<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-02-17 at 00:38:50.
 */
class AccessurleditsessionstourlTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Accessurleditsessionstourl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Accessurleditsessionstourl;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert () === false.
     *
     * @covers Accessurleditsessionstourl::search_sessions
     */
    public function testSearch_sessions()
    {
        $this->assertSame(
          false,
          $this->object->search_sessions()
        );
    }
}
