<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-01 at 14:44:08.
 */
class AccessForbiddenTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var AccessForbidden
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AccessForbidden;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers AccessForbidden::instance
     * @todo   Implement testInstance().
     */
    public function testInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccessForbidden::can_edit
     * @todo   Implement testCan_edit().
     */
    public function testCan_edit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccessForbidden::can_view
     * @todo   Implement testCan_view().
     */
    public function testCan_view()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccessForbidden::authorize
     * @todo   Implement testAuthorize().
     */
    public function testAuthorize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
