<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-02-17 at 01:03:12.
 */
class AddManySessionToCategoryFunctionsTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var AddManySessionToCategoryFunctions
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        require_once dirname(__FILE__).'/../../../main/inc/global.inc.php';
        $this->object = new AddManySessionToCategoryFunctions;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert () !== ''.
     *
     * @covers AddManySessionToCategoryFunctions::search_courses
     */
    public function testSearch_courses()
    {
        $this->assertNotSame(
          '',
          $this->object->search_courses()
        );
    }

    /**
     * Generated from @assert ('abc','single') !== ''.
     *
     * @covers AddManySessionToCategoryFunctions::search_courses
     */
    public function testSearch_courses2()
    {
        $this->assertNotSame(
          '',
          $this->object->search_courses('abc','single')
        );
    }
}
