<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-02-17 at 01:03:12.
 */
class AddManySessionToCategoryFunctionsTest extends BaseWebTestCase
{
    /**
     * @var AddManySessionToCategoryFunctions
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new AddManySessionToCategoryFunctions;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert ('abc','single') !== ''.
     *
     * @covers AddManySessionToCategoryFunctions::search_courses
     */
    public function testSearch_courses()
    {
        /*$this->assertNotSame(
          '',
          $this->object->search_courses('abc','single')
        );*/
    }
}
