<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-01 at 14:44:08.
 */
class CurrentCourseTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var CurrentCourse
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CurrentCourse;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers CurrentCourse::instance
     * @todo   Implement testInstance().
     */
    public function testInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::is_empty
     * @todo   Implement testIs_empty().
     */
    public function testIs_empty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::data
     * @todo   Implement testData().
     */
    public function testData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::real_id
     * @todo   Implement testReal_id().
     */
    public function testReal_id()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::code
     * @todo   Implement testCode().
     */
    public function testCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::name
     * @todo   Implement testName().
     */
    public function testName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::title
     * @todo   Implement testTitle().
     */
    public function testTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::official_code
     * @todo   Implement testOfficial_code().
     */
    public function testOfficial_code()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::sys_code
     * @todo   Implement testSys_code().
     */
    public function testSys_code()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::path
     * @todo   Implement testPath().
     */
    public function testPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::db_name
     * @todo   Implement testDb_name().
     */
    public function testDb_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::db_name_glu
     * @todo   Implement testDb_name_glu().
     */
    public function testDb_name_glu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::titular
     * @todo   Implement testTitular().
     */
    public function testTitular()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::language
     * @todo   Implement testLanguage().
     */
    public function testLanguage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::category_code
     * @todo   Implement testCategory_code().
     */
    public function testCategory_code()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::category_ame
     * @todo   Implement testCategory_ame().
     */
    public function testCategory_ame()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::visibility
     * @todo   Implement testVisibility().
     */
    public function testVisibility()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::subscribe_allowed
     * @todo   Implement testSubscribe_allowed().
     */
    public function testSubscribe_allowed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::unsubscribe_allowed
     * @todo   Implement testUnsubscribe_allowed().
     */
    public function testUnsubscribe_allowed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::activate_legal
     * @todo   Implement testActivate_legal().
     */
    public function testActivate_legal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::show_score
     * @todo   Implement testShow_score().
     */
    public function testShow_score()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::extrnal_link
     * @todo   Implement testExtrnal_link().
     */
    public function testExtrnal_link()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::user
     * @todo   Implement testUser().
     */
    public function testUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CurrentCourse::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
