<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-07 at 09:33:51.
 */
class DisplayTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Display
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Display;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Display::display_header
     * @todo   Implement testDisplay_header().
     */
    public function testDisplay_header()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::display_reduced_header
     * @todo   Implement testDisplay_reduced_header().
     */
    public function testDisplay_reduced_header()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::display_no_header
     * @todo   Implement testDisplay_no_header().
     */
    public function testDisplay_no_header()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::set_header
     * @todo   Implement testSet_header().
     */
    public function testSet_header()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::display_footer
     * @todo   Implement testDisplay_footer().
     */
    public function testDisplay_footer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::page
     * @todo   Implement testPage().
     */
    public function testPage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::display_introduction_section
     * @todo   Implement testDisplay_introduction_section().
     */
    public function testDisplay_introduction_section()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::return_introduction_section
     * @todo   Implement testReturn_introduction_section().
     */
    public function testReturn_introduction_section()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::display_localised_html_file
     * @todo   Implement testDisplay_localised_html_file().
     */
    public function testDisplay_localised_html_file()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::display_sortable_table
     * @todo   Implement testDisplay_sortable_table().
     */
    public function testDisplay_sortable_table()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::display_sortable_grid
     * @todo   Implement testDisplay_sortable_grid().
     */
    public function testDisplay_sortable_grid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::return_sortable_grid
     * @todo   Implement testReturn_sortable_grid().
     */
    public function testReturn_sortable_grid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::display_sortable_config_table
     * @todo   Implement testDisplay_sortable_config_table().
     */
    public function testDisplay_sortable_config_table()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::display_normal_message
     * @todo   Implement testDisplay_normal_message().
     */
    public function testDisplay_normal_message()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::display_warning_message
     * @todo   Implement testDisplay_warning_message().
     */
    public function testDisplay_warning_message()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::display_confirmation_message
     * @todo   Implement testDisplay_confirmation_message().
     */
    public function testDisplay_confirmation_message()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::display_error_message
     * @todo   Implement testDisplay_error_message().
     */
    public function testDisplay_error_message()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::return_message_and_translate
     * @todo   Implement testReturn_message_and_translate().
     */
    public function testReturn_message_and_translate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::return_message
     * @todo   Implement testReturn_message().
     */
    public function testReturn_message()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::encrypted_mailto_link
     * @todo   Implement testEncrypted_mailto_link().
     */
    public function testEncrypted_mailto_link()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::icon_mailto_link
     * @todo   Implement testIcon_mailto_link().
     */
    public function testIcon_mailto_link()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::get_platform_home_link_html
     * @todo   Implement testGet_platform_home_link_html().
     */
    public function testGet_platform_home_link_html()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::get_alphabet_options
     * @todo   Implement testGet_alphabet_options().
     */
    public function testGet_alphabet_options()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::get_numeric_options
     * @todo   Implement testGet_numeric_options().
     */
    public function testGet_numeric_options()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::show_course_navigation_menu
     * @todo   Implement testShow_course_navigation_menu().
     */
    public function testShow_course_navigation_menu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::display_icon
     * @todo   Implement testDisplay_icon().
     */
    public function testDisplay_icon()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::return_icon
     * @todo   Implement testReturn_icon().
     */
    public function testReturn_icon()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::img
     * @todo   Implement testImg().
     */
    public function testImg()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::tag
     * @todo   Implement testTag().
     */
    public function testTag()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::url
     * @todo   Implement testUrl().
     */
    public function testUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::div
     * @todo   Implement testDiv().
     */
    public function testDiv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::span
     * @todo   Implement testSpan().
     */
    public function testSpan()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::input
     * @todo   Implement testInput().
     */
    public function testInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::button
     * @todo   Implement testButton().
     */
    public function testButton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::select
     * @todo   Implement testSelect().
     */
    public function testSelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::tabs
     * @todo   Implement testTabs().
     */
    public function testTabs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::tabs_only_link
     * @todo   Implement testTabs_only_link().
     */
    public function testTabs_only_link()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::grid_html
     * @todo   Implement testGrid_html().
     */
    public function testGrid_html()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::form_row
     * @todo   Implement testForm_row().
     */
    public function testForm_row()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::grid_js
     * @todo   Implement testGrid_js().
     */
    public function testGrid_js()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::table
     * @todo   Implement testTable().
     */
    public function testTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::show_notification
     * @todo   Implement testShow_notification().
     */
    public function testShow_notification()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::display_digest
     * @todo   Implement testDisplay_digest().
     */
    public function testDisplay_digest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::get_session_title_box
     * @todo   Implement testGet_session_title_box().
     */
    public function testGet_session_title_box()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::return_rating_system
     * @todo   Implement testReturn_rating_system().
     */
    public function testReturn_rating_system()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::return_default_table_class
     * @todo   Implement testReturn_default_table_class().
     */
    public function testReturn_default_table_class()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::page_header
     * @todo   Implement testPage_header().
     */
    public function testPage_header()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::page_header_and_translate
     * @todo   Implement testPage_header_and_translate().
     */
    public function testPage_header_and_translate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::page_subheader_and_translate
     * @todo   Implement testPage_subheader_and_translate().
     */
    public function testPage_subheader_and_translate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::page_subheader
     * @todo   Implement testPage_subheader().
     */
    public function testPage_subheader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::page_subheader2
     * @todo   Implement testPage_subheader2().
     */
    public function testPage_subheader2()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::page_subheader3
     * @todo   Implement testPage_subheader3().
     */
    public function testPage_subheader3()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::description
     * @todo   Implement testDescription().
     */
    public function testDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::bar_progress
     * @todo   Implement testBar_progress().
     */
    public function testBar_progress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::badge
     * @todo   Implement testBadge().
     */
    public function testBadge()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::badge_group
     * @todo   Implement testBadge_group().
     */
    public function testBadge_group()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::label
     * @todo   Implement testLabel().
     */
    public function testLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::actions
     * @todo   Implement testActions().
     */
    public function testActions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::tip
     * @todo   Implement testTip().
     */
    public function testTip()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::generate_accordion
     * @todo   Implement testGenerate_accordion().
     */
    public function testGenerate_accordion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Display::group_button
     * @todo   Implement testGroup_button().
     */
    public function testGroup_button()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
