<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-07 at 09:22:59.
 */
class ImagickPixelTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ImagickPixel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ImagickPixel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ImagickPixel::gethsl
     * @todo   Implement testGethsl().
     */
    public function testGethsl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ImagickPixel::sethsl
     * @todo   Implement testSethsl().
     */
    public function testSethsl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ImagickPixel::getcolorvaluequantum
     * @todo   Implement testGetcolorvaluequantum().
     */
    public function testGetcolorvaluequantum()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ImagickPixel::setcolorvaluequantum
     * @todo   Implement testSetcolorvaluequantum().
     */
    public function testSetcolorvaluequantum()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ImagickPixel::getindex
     * @todo   Implement testGetindex().
     */
    public function testGetindex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ImagickPixel::setindex
     * @todo   Implement testSetindex().
     */
    public function testSetindex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ImagickPixel::setcolor
     * @todo   Implement testSetcolor().
     */
    public function testSetcolor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ImagickPixel::setcolorvalue
     * @todo   Implement testSetcolorvalue().
     */
    public function testSetcolorvalue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ImagickPixel::getcolorvalue
     * @todo   Implement testGetcolorvalue().
     */
    public function testGetcolorvalue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ImagickPixel::clear
     * @todo   Implement testClear().
     */
    public function testClear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ImagickPixel::destroy
     * @todo   Implement testDestroy().
     */
    public function testDestroy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ImagickPixel::issimilar
     * @todo   Implement testIssimilar().
     */
    public function testIssimilar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ImagickPixel::getcolor
     * @todo   Implement testGetcolor().
     */
    public function testGetcolor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ImagickPixel::getcolorasstring
     * @todo   Implement testGetcolorasstring().
     */
    public function testGetcolorasstring()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ImagickPixel::getcolorcount
     * @todo   Implement testGetcolorcount().
     */
    public function testGetcolorcount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ImagickPixel::setcolorcount
     * @todo   Implement testSetcolorcount().
     */
    public function testSetcolorcount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ImagickPixel::clone
     * @todo   Implement testClone().
     */
    public function testClone()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
