<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-07 at 09:29:52.
 */
class ImportTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Import
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Import;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Import::csv_reader
     * @todo   Implement testCsv_reader().
     */
    public function testCsv_reader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Import::csv_to_array
     * @todo   Implement testCsv_to_array().
     */
    public function testCsv_to_array()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
