<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-07 at 09:22:58.
 */
class mysqli_resultTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var mysqli_result
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new mysqli_result;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers mysqli_result::close
     * @todo   Implement testClose().
     */
    public function testClose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mysqli_result::free
     * @todo   Implement testFree().
     */
    public function testFree()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mysqli_result::data_seek
     * @todo   Implement testData_seek().
     */
    public function testData_seek()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mysqli_result::fetch_field
     * @todo   Implement testFetch_field().
     */
    public function testFetch_field()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mysqli_result::fetch_fields
     * @todo   Implement testFetch_fields().
     */
    public function testFetch_fields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mysqli_result::fetch_field_direct
     * @todo   Implement testFetch_field_direct().
     */
    public function testFetch_field_direct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mysqli_result::fetch_array
     * @todo   Implement testFetch_array().
     */
    public function testFetch_array()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mysqli_result::fetch_assoc
     * @todo   Implement testFetch_assoc().
     */
    public function testFetch_assoc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mysqli_result::fetch_object
     * @todo   Implement testFetch_object().
     */
    public function testFetch_object()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mysqli_result::fetch_row
     * @todo   Implement testFetch_row().
     */
    public function testFetch_row()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mysqli_result::field_seek
     * @todo   Implement testField_seek().
     */
    public function testField_seek()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mysqli_result::free_result
     * @todo   Implement testFree_result().
     */
    public function testFree_result()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
