<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-07 at 09:22:56.
 */
class PharTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Phar
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Phar;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Phar::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::addEmptyDir
     * @todo   Implement testAddEmptyDir().
     */
    public function testAddEmptyDir()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::addFile
     * @todo   Implement testAddFile().
     */
    public function testAddFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::addFromString
     * @todo   Implement testAddFromString().
     */
    public function testAddFromString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::buildFromDirectory
     * @todo   Implement testBuildFromDirectory().
     */
    public function testBuildFromDirectory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::buildFromIterator
     * @todo   Implement testBuildFromIterator().
     */
    public function testBuildFromIterator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::compressFiles
     * @todo   Implement testCompressFiles().
     */
    public function testCompressFiles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::decompressFiles
     * @todo   Implement testDecompressFiles().
     */
    public function testDecompressFiles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::compress
     * @todo   Implement testCompress().
     */
    public function testCompress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::decompress
     * @todo   Implement testDecompress().
     */
    public function testDecompress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::convertToExecutable
     * @todo   Implement testConvertToExecutable().
     */
    public function testConvertToExecutable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::convertToData
     * @todo   Implement testConvertToData().
     */
    public function testConvertToData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::copy
     * @todo   Implement testCopy().
     */
    public function testCopy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::count
     * @todo   Implement testCount().
     */
    public function testCount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::delMetadata
     * @todo   Implement testDelMetadata().
     */
    public function testDelMetadata()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::extractTo
     * @todo   Implement testExtractTo().
     */
    public function testExtractTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::getAlias
     * @todo   Implement testGetAlias().
     */
    public function testGetAlias()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::getPath
     * @todo   Implement testGetPath().
     */
    public function testGetPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::getMetadata
     * @todo   Implement testGetMetadata().
     */
    public function testGetMetadata()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::getModified
     * @todo   Implement testGetModified().
     */
    public function testGetModified()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::getSignature
     * @todo   Implement testGetSignature().
     */
    public function testGetSignature()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::getStub
     * @todo   Implement testGetStub().
     */
    public function testGetStub()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::getVersion
     * @todo   Implement testGetVersion().
     */
    public function testGetVersion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::hasMetadata
     * @todo   Implement testHasMetadata().
     */
    public function testHasMetadata()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::isBuffering
     * @todo   Implement testIsBuffering().
     */
    public function testIsBuffering()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::isCompressed
     * @todo   Implement testIsCompressed().
     */
    public function testIsCompressed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::isFileFormat
     * @todo   Implement testIsFileFormat().
     */
    public function testIsFileFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::isWritable
     * @todo   Implement testIsWritable().
     */
    public function testIsWritable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::offsetExists
     * @todo   Implement testOffsetExists().
     */
    public function testOffsetExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::offsetGet
     * @todo   Implement testOffsetGet().
     */
    public function testOffsetGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::offsetSet
     * @todo   Implement testOffsetSet().
     */
    public function testOffsetSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::offsetUnset
     * @todo   Implement testOffsetUnset().
     */
    public function testOffsetUnset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::setAlias
     * @todo   Implement testSetAlias().
     */
    public function testSetAlias()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::setDefaultStub
     * @todo   Implement testSetDefaultStub().
     */
    public function testSetDefaultStub()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::setMetadata
     * @todo   Implement testSetMetadata().
     */
    public function testSetMetadata()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::setSignatureAlgorithm
     * @todo   Implement testSetSignatureAlgorithm().
     */
    public function testSetSignatureAlgorithm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::setStub
     * @todo   Implement testSetStub().
     */
    public function testSetStub()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::startBuffering
     * @todo   Implement testStartBuffering().
     */
    public function testStartBuffering()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::stopBuffering
     * @todo   Implement testStopBuffering().
     */
    public function testStopBuffering()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::apiVersion
     * @todo   Implement testApiVersion().
     */
    public function testApiVersion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::canCompress
     * @todo   Implement testCanCompress().
     */
    public function testCanCompress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::canWrite
     * @todo   Implement testCanWrite().
     */
    public function testCanWrite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::createDefaultStub
     * @todo   Implement testCreateDefaultStub().
     */
    public function testCreateDefaultStub()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::getSupportedCompression
     * @todo   Implement testGetSupportedCompression().
     */
    public function testGetSupportedCompression()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::getSupportedSignatures
     * @todo   Implement testGetSupportedSignatures().
     */
    public function testGetSupportedSignatures()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::interceptFileFuncs
     * @todo   Implement testInterceptFileFuncs().
     */
    public function testInterceptFileFuncs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::isValidPharFilename
     * @todo   Implement testIsValidPharFilename().
     */
    public function testIsValidPharFilename()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::loadPhar
     * @todo   Implement testLoadPhar().
     */
    public function testLoadPhar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::mapPhar
     * @todo   Implement testMapPhar().
     */
    public function testMapPhar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::running
     * @todo   Implement testRunning().
     */
    public function testRunning()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::mount
     * @todo   Implement testMount().
     */
    public function testMount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::mungServer
     * @todo   Implement testMungServer().
     */
    public function testMungServer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::unlinkArchive
     * @todo   Implement testUnlinkArchive().
     */
    public function testUnlinkArchive()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phar::webPhar
     * @todo   Implement testWebPhar().
     */
    public function testWebPhar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
