<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-07 at 09:22:51.
 */
class RecursiveDirectoryIteratorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var RecursiveDirectoryIterator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RecursiveDirectoryIterator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers RecursiveDirectoryIterator::hasChildren
     * @todo   Implement testHasChildren().
     */
    public function testHasChildren()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RecursiveDirectoryIterator::getChildren
     * @todo   Implement testGetChildren().
     */
    public function testGetChildren()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RecursiveDirectoryIterator::getSubPath
     * @todo   Implement testGetSubPath().
     */
    public function testGetSubPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RecursiveDirectoryIterator::getSubPathname
     * @todo   Implement testGetSubPathname().
     */
    public function testGetSubPathname()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
