<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-07 at 09:22:53.
 */
class ReflectionFunctionAbstractTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ReflectionFunctionAbstract
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ReflectionFunctionAbstract;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ReflectionFunctionAbstract::inNamespace
     * @todo   Implement testInNamespace().
     */
    public function testInNamespace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::isClosure
     * @todo   Implement testIsClosure().
     */
    public function testIsClosure()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::isDeprecated
     * @todo   Implement testIsDeprecated().
     */
    public function testIsDeprecated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::isInternal
     * @todo   Implement testIsInternal().
     */
    public function testIsInternal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::isUserDefined
     * @todo   Implement testIsUserDefined().
     */
    public function testIsUserDefined()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::getClosureThis
     * @todo   Implement testGetClosureThis().
     */
    public function testGetClosureThis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::getClosureScopeClass
     * @todo   Implement testGetClosureScopeClass().
     */
    public function testGetClosureScopeClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::getDocComment
     * @todo   Implement testGetDocComment().
     */
    public function testGetDocComment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::getEndLine
     * @todo   Implement testGetEndLine().
     */
    public function testGetEndLine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::getExtension
     * @todo   Implement testGetExtension().
     */
    public function testGetExtension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::getExtensionName
     * @todo   Implement testGetExtensionName().
     */
    public function testGetExtensionName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::getFileName
     * @todo   Implement testGetFileName().
     */
    public function testGetFileName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::getNamespaceName
     * @todo   Implement testGetNamespaceName().
     */
    public function testGetNamespaceName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::getNumberOfParameters
     * @todo   Implement testGetNumberOfParameters().
     */
    public function testGetNumberOfParameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::getNumberOfRequiredParameters
     * @todo   Implement testGetNumberOfRequiredParameters().
     */
    public function testGetNumberOfRequiredParameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::getParameters
     * @todo   Implement testGetParameters().
     */
    public function testGetParameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::getShortName
     * @todo   Implement testGetShortName().
     */
    public function testGetShortName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::getStartLine
     * @todo   Implement testGetStartLine().
     */
    public function testGetStartLine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::getStaticVariables
     * @todo   Implement testGetStaticVariables().
     */
    public function testGetStaticVariables()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionFunctionAbstract::returnsReference
     * @todo   Implement testReturnsReference().
     */
    public function testReturnsReference()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
