<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-07 at 09:22:53.
 */
class ReflectionClassTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ReflectionClass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ReflectionClass;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ReflectionClass::export
     * @todo   Implement testExport().
     */
    public function testExport()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::isInternal
     * @todo   Implement testIsInternal().
     */
    public function testIsInternal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::isUserDefined
     * @todo   Implement testIsUserDefined().
     */
    public function testIsUserDefined()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::isInstantiable
     * @todo   Implement testIsInstantiable().
     */
    public function testIsInstantiable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::isCloneable
     * @todo   Implement testIsCloneable().
     */
    public function testIsCloneable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getFileName
     * @todo   Implement testGetFileName().
     */
    public function testGetFileName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getStartLine
     * @todo   Implement testGetStartLine().
     */
    public function testGetStartLine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getEndLine
     * @todo   Implement testGetEndLine().
     */
    public function testGetEndLine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getDocComment
     * @todo   Implement testGetDocComment().
     */
    public function testGetDocComment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getConstructor
     * @todo   Implement testGetConstructor().
     */
    public function testGetConstructor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::hasMethod
     * @todo   Implement testHasMethod().
     */
    public function testHasMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getMethod
     * @todo   Implement testGetMethod().
     */
    public function testGetMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getMethods
     * @todo   Implement testGetMethods().
     */
    public function testGetMethods()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::hasProperty
     * @todo   Implement testHasProperty().
     */
    public function testHasProperty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getProperty
     * @todo   Implement testGetProperty().
     */
    public function testGetProperty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getProperties
     * @todo   Implement testGetProperties().
     */
    public function testGetProperties()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::hasConstant
     * @todo   Implement testHasConstant().
     */
    public function testHasConstant()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getConstants
     * @todo   Implement testGetConstants().
     */
    public function testGetConstants()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getConstant
     * @todo   Implement testGetConstant().
     */
    public function testGetConstant()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getInterfaces
     * @todo   Implement testGetInterfaces().
     */
    public function testGetInterfaces()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getInterfaceNames
     * @todo   Implement testGetInterfaceNames().
     */
    public function testGetInterfaceNames()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::isInterface
     * @todo   Implement testIsInterface().
     */
    public function testIsInterface()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getTraits
     * @todo   Implement testGetTraits().
     */
    public function testGetTraits()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getTraitNames
     * @todo   Implement testGetTraitNames().
     */
    public function testGetTraitNames()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getTraitAliases
     * @todo   Implement testGetTraitAliases().
     */
    public function testGetTraitAliases()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::isTrait
     * @todo   Implement testIsTrait().
     */
    public function testIsTrait()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::isAbstract
     * @todo   Implement testIsAbstract().
     */
    public function testIsAbstract()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::isFinal
     * @todo   Implement testIsFinal().
     */
    public function testIsFinal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getModifiers
     * @todo   Implement testGetModifiers().
     */
    public function testGetModifiers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::isInstance
     * @todo   Implement testIsInstance().
     */
    public function testIsInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::newInstance
     * @todo   Implement testNewInstance().
     */
    public function testNewInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::newInstanceWithoutConstructor
     * @todo   Implement testNewInstanceWithoutConstructor().
     */
    public function testNewInstanceWithoutConstructor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::newInstanceArgs
     * @todo   Implement testNewInstanceArgs().
     */
    public function testNewInstanceArgs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getParentClass
     * @todo   Implement testGetParentClass().
     */
    public function testGetParentClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::isSubclassOf
     * @todo   Implement testIsSubclassOf().
     */
    public function testIsSubclassOf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getStaticProperties
     * @todo   Implement testGetStaticProperties().
     */
    public function testGetStaticProperties()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getStaticPropertyValue
     * @todo   Implement testGetStaticPropertyValue().
     */
    public function testGetStaticPropertyValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::setStaticPropertyValue
     * @todo   Implement testSetStaticPropertyValue().
     */
    public function testSetStaticPropertyValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getDefaultProperties
     * @todo   Implement testGetDefaultProperties().
     */
    public function testGetDefaultProperties()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::isIterateable
     * @todo   Implement testIsIterateable().
     */
    public function testIsIterateable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::implementsInterface
     * @todo   Implement testImplementsInterface().
     */
    public function testImplementsInterface()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getExtension
     * @todo   Implement testGetExtension().
     */
    public function testGetExtension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getExtensionName
     * @todo   Implement testGetExtensionName().
     */
    public function testGetExtensionName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::inNamespace
     * @todo   Implement testInNamespace().
     */
    public function testInNamespace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getNamespaceName
     * @todo   Implement testGetNamespaceName().
     */
    public function testGetNamespaceName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReflectionClass::getShortName
     * @todo   Implement testGetShortName().
     */
    public function testGetShortName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
