<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-07 at 09:22:50.
 */
class RegexIteratorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var RegexIterator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RegexIterator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers RegexIterator::accept
     * @todo   Implement testAccept().
     */
    public function testAccept()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegexIterator::getMode
     * @todo   Implement testGetMode().
     */
    public function testGetMode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegexIterator::setMode
     * @todo   Implement testSetMode().
     */
    public function testSetMode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegexIterator::getFlags
     * @todo   Implement testGetFlags().
     */
    public function testGetFlags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegexIterator::setFlags
     * @todo   Implement testSetFlags().
     */
    public function testSetFlags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegexIterator::getPregFlags
     * @todo   Implement testGetPregFlags().
     */
    public function testGetPregFlags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegexIterator::setPregFlags
     * @todo   Implement testSetPregFlags().
     */
    public function testSetPregFlags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegexIterator::getRegex
     * @todo   Implement testGetRegex().
     */
    public function testGetRegex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
