<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-01 at 14:44:10.
 */
class UserApiKeyManagerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var UserApiKeyManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UserApiKeyManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers UserApiKeyManager::default_service
     * @todo   Implement testDefault_service().
     */
    public function testDefault_service()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UserApiKeyManager::end_of_time
     * @todo   Implement testEnd_of_time().
     */
    public function testEnd_of_time()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UserApiKeyManager::get_by_id
     * @todo   Implement testGet_by_id().
     */
    public function testGet_by_id()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UserApiKeyManager::create_temp_token
     * @todo   Implement testCreate_temp_token().
     */
    public function testCreate_temp_token()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UserApiKeyManager::create_token
     * @todo   Implement testCreate_token().
     */
    public function testCreate_token()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
