<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-07 at 09:22:55.
 */
class XMLReaderTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var XMLReader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new XMLReader;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers XMLReader::close
     * @todo   Implement testClose().
     */
    public function testClose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::getAttribute
     * @todo   Implement testGetAttribute().
     */
    public function testGetAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::getAttributeNo
     * @todo   Implement testGetAttributeNo().
     */
    public function testGetAttributeNo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::getAttributeNs
     * @todo   Implement testGetAttributeNs().
     */
    public function testGetAttributeNs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::getParserProperty
     * @todo   Implement testGetParserProperty().
     */
    public function testGetParserProperty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::isValid
     * @todo   Implement testIsValid().
     */
    public function testIsValid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::lookupNamespace
     * @todo   Implement testLookupNamespace().
     */
    public function testLookupNamespace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::moveToAttributeNo
     * @todo   Implement testMoveToAttributeNo().
     */
    public function testMoveToAttributeNo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::moveToAttribute
     * @todo   Implement testMoveToAttribute().
     */
    public function testMoveToAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::moveToAttributeNs
     * @todo   Implement testMoveToAttributeNs().
     */
    public function testMoveToAttributeNs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::moveToElement
     * @todo   Implement testMoveToElement().
     */
    public function testMoveToElement()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::moveToFirstAttribute
     * @todo   Implement testMoveToFirstAttribute().
     */
    public function testMoveToFirstAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::moveToNextAttribute
     * @todo   Implement testMoveToNextAttribute().
     */
    public function testMoveToNextAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::open
     * @todo   Implement testOpen().
     */
    public function testOpen()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::read
     * @todo   Implement testRead().
     */
    public function testRead()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::next
     * @todo   Implement testNext().
     */
    public function testNext()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::readInnerXml
     * @todo   Implement testReadInnerXml().
     */
    public function testReadInnerXml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::readOuterXml
     * @todo   Implement testReadOuterXml().
     */
    public function testReadOuterXml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::readString
     * @todo   Implement testReadString().
     */
    public function testReadString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::setSchema
     * @todo   Implement testSetSchema().
     */
    public function testSetSchema()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::setParserProperty
     * @todo   Implement testSetParserProperty().
     */
    public function testSetParserProperty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::setRelaxNGSchema
     * @todo   Implement testSetRelaxNGSchema().
     */
    public function testSetRelaxNGSchema()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::setRelaxNGSchemaSource
     * @todo   Implement testSetRelaxNGSchemaSource().
     */
    public function testSetRelaxNGSchemaSource()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::XML
     * @todo   Implement testXML().
     */
    public function testXML()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XMLReader::expand
     * @todo   Implement testExpand().
     */
    public function testExpand()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
