<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-07 at 09:22:55.
 */
class ZipArchiveTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ZipArchive
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ZipArchive;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ZipArchive::open
     * @todo   Implement testOpen().
     */
    public function testOpen()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::close
     * @todo   Implement testClose().
     */
    public function testClose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::getStatusString
     * @todo   Implement testGetStatusString().
     */
    public function testGetStatusString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::addEmptyDir
     * @todo   Implement testAddEmptyDir().
     */
    public function testAddEmptyDir()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::addFromString
     * @todo   Implement testAddFromString().
     */
    public function testAddFromString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::addFile
     * @todo   Implement testAddFile().
     */
    public function testAddFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::addGlob
     * @todo   Implement testAddGlob().
     */
    public function testAddGlob()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::addPattern
     * @todo   Implement testAddPattern().
     */
    public function testAddPattern()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::renameIndex
     * @todo   Implement testRenameIndex().
     */
    public function testRenameIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::renameName
     * @todo   Implement testRenameName().
     */
    public function testRenameName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::setArchiveComment
     * @todo   Implement testSetArchiveComment().
     */
    public function testSetArchiveComment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::getArchiveComment
     * @todo   Implement testGetArchiveComment().
     */
    public function testGetArchiveComment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::setCommentIndex
     * @todo   Implement testSetCommentIndex().
     */
    public function testSetCommentIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::setCommentName
     * @todo   Implement testSetCommentName().
     */
    public function testSetCommentName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::getCommentIndex
     * @todo   Implement testGetCommentIndex().
     */
    public function testGetCommentIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::getCommentName
     * @todo   Implement testGetCommentName().
     */
    public function testGetCommentName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::deleteIndex
     * @todo   Implement testDeleteIndex().
     */
    public function testDeleteIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::deleteName
     * @todo   Implement testDeleteName().
     */
    public function testDeleteName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::statName
     * @todo   Implement testStatName().
     */
    public function testStatName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::statIndex
     * @todo   Implement testStatIndex().
     */
    public function testStatIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::locateName
     * @todo   Implement testLocateName().
     */
    public function testLocateName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::getNameIndex
     * @todo   Implement testGetNameIndex().
     */
    public function testGetNameIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::unchangeArchive
     * @todo   Implement testUnchangeArchive().
     */
    public function testUnchangeArchive()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::unchangeAll
     * @todo   Implement testUnchangeAll().
     */
    public function testUnchangeAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::unchangeIndex
     * @todo   Implement testUnchangeIndex().
     */
    public function testUnchangeIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::unchangeName
     * @todo   Implement testUnchangeName().
     */
    public function testUnchangeName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::extractTo
     * @todo   Implement testExtractTo().
     */
    public function testExtractTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::getFromName
     * @todo   Implement testGetFromName().
     */
    public function testGetFromName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::getFromIndex
     * @todo   Implement testGetFromIndex().
     */
    public function testGetFromIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ZipArchive::getStream
     * @todo   Implement testGetStream().
     */
    public function testGetStream()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
