<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class Announcement extends \CourseEntity
{
    /**
     * @return \Entity\Repository\AnnouncementRepository
     */
     public static function repository(){
        return \Entity\Repository\AnnouncementRepository::instance();
    }

    /**
     * @return \Entity\Announcement
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $c_id
     */
    protected $c_id;

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var text $title
     */
    protected $title;

    /**
     * @var text $content
     */
    protected $content;

    /**
     * @var date $end_date
     */
    protected $end_date;

    /**
     * @var integer $display_order
     */
    protected $display_order;

    /**
     * @var boolean $email_sent
     */
    protected $email_sent;

    /**
     * @var integer $session_id
     */
    protected $session_id;


    /**
     * Set c_id
     *
     * @param integer $value
     * @return Announcement
     */
    public function set_c_id($value)
    {
        $this->c_id = $value;
        return $this;
    }

    /**
     * Get c_id
     *
     * @return integer 
     */
    public function get_c_id()
    {
        return $this->c_id;
    }

    /**
     * Set id
     *
     * @param integer $value
     * @return Announcement
     */
    public function set_id($value)
    {
        $this->id = $value;
        return $this;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param text $value
     * @return Announcement
     */
    public function set_title($value)
    {
        $this->title = $value;
        return $this;
    }

    /**
     * Get title
     *
     * @return text 
     */
    public function get_title()
    {
        return $this->title;
    }

    /**
     * Set content
     *
     * @param text $value
     * @return Announcement
     */
    public function set_content($value)
    {
        $this->content = $value;
        return $this;
    }

    /**
     * Get content
     *
     * @return text 
     */
    public function get_content()
    {
        return $this->content;
    }

    /**
     * Set end_date
     *
     * @param date $value
     * @return Announcement
     */
    public function set_end_date($value)
    {
        $this->end_date = $value;
        return $this;
    }

    /**
     * Get end_date
     *
     * @return date 
     */
    public function get_end_date()
    {
        return $this->end_date;
    }

    /**
     * Set display_order
     *
     * @param integer $value
     * @return Announcement
     */
    public function set_display_order($value)
    {
        $this->display_order = $value;
        return $this;
    }

    /**
     * Get display_order
     *
     * @return integer 
     */
    public function get_display_order()
    {
        return $this->display_order;
    }

    /**
     * Set email_sent
     *
     * @param boolean $value
     * @return Announcement
     */
    public function set_email_sent($value)
    {
        $this->email_sent = $value;
        return $this;
    }

    /**
     * Get email_sent
     *
     * @return boolean 
     */
    public function get_email_sent()
    {
        return $this->email_sent;
    }

    /**
     * Set session_id
     *
     * @param integer $value
     * @return Announcement
     */
    public function set_session_id($value)
    {
        $this->session_id = $value;
        return $this;
    }

    /**
     * Get session_id
     *
     * @return integer 
     */
    public function get_session_id()
    {
        return $this->session_id;
    }
}