<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class Chat extends \Entity
{
    /**
     * @return \Entity\Repository\ChatRepository
     */
     public static function repository(){
        return \Entity\Repository\ChatRepository::instance();
    }

    /**
     * @return \Entity\Chat
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var integer $from_user
     */
    protected $from_user;

    /**
     * @var integer $to_user
     */
    protected $to_user;

    /**
     * @var text $message
     */
    protected $message;

    /**
     * @var datetime $sent
     */
    protected $sent;

    /**
     * @var integer $recd
     */
    protected $recd;


    /**
     * Get id
     *
     * @return integer 
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * Set from_user
     *
     * @param integer $value
     * @return Chat
     */
    public function set_from_user($value)
    {
        $this->from_user = $value;
        return $this;
    }

    /**
     * Get from_user
     *
     * @return integer 
     */
    public function get_from_user()
    {
        return $this->from_user;
    }

    /**
     * Set to_user
     *
     * @param integer $value
     * @return Chat
     */
    public function set_to_user($value)
    {
        $this->to_user = $value;
        return $this;
    }

    /**
     * Get to_user
     *
     * @return integer 
     */
    public function get_to_user()
    {
        return $this->to_user;
    }

    /**
     * Set message
     *
     * @param text $value
     * @return Chat
     */
    public function set_message($value)
    {
        $this->message = $value;
        return $this;
    }

    /**
     * Get message
     *
     * @return text 
     */
    public function get_message()
    {
        return $this->message;
    }

    /**
     * Set sent
     *
     * @param datetime $value
     * @return Chat
     */
    public function set_sent($value)
    {
        $this->sent = $value;
        return $this;
    }

    /**
     * Get sent
     *
     * @return datetime 
     */
    public function get_sent()
    {
        return $this->sent;
    }

    /**
     * Set recd
     *
     * @param integer $value
     * @return Chat
     */
    public function set_recd($value)
    {
        $this->recd = $value;
        return $this;
    }

    /**
     * Get recd
     *
     * @return integer 
     */
    public function get_recd()
    {
        return $this->recd;
    }
}