<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class EventSent extends \Entity
{
    /**
     * @return \Entity\Repository\EventSentRepository
     */
     public static function repository(){
        return \Entity\Repository\EventSentRepository::instance();
    }

    /**
     * @return \Entity\EventSent
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var integer $user_from
     */
    protected $user_from;

    /**
     * @var integer $user_to
     */
    protected $user_to;

    /**
     * @var string $event_type_name
     */
    protected $event_type_name;


    /**
     * Get id
     *
     * @return integer 
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * Set user_from
     *
     * @param integer $value
     * @return EventSent
     */
    public function set_user_from($value)
    {
        $this->user_from = $value;
        return $this;
    }

    /**
     * Get user_from
     *
     * @return integer 
     */
    public function get_user_from()
    {
        return $this->user_from;
    }

    /**
     * Set user_to
     *
     * @param integer $value
     * @return EventSent
     */
    public function set_user_to($value)
    {
        $this->user_to = $value;
        return $this;
    }

    /**
     * Get user_to
     *
     * @return integer 
     */
    public function get_user_to()
    {
        return $this->user_to;
    }

    /**
     * Set event_type_name
     *
     * @param string $value
     * @return EventSent
     */
    public function set_event_type_name($value)
    {
        $this->event_type_name = $value;
        return $this;
    }

    /**
     * Get event_type_name
     *
     * @return string 
     */
    public function get_event_type_name()
    {
        return $this->event_type_name;
    }
}