<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class GradeComponents extends \Entity
{
    /**
     * @return \Entity\Repository\GradeComponentsRepository
     */
     public static function repository(){
        return \Entity\Repository\GradeComponentsRepository::instance();
    }

    /**
     * @return \Entity\GradeComponents
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var string $percentage
     */
    protected $percentage;

    /**
     * @var string $title
     */
    protected $title;

    /**
     * @var string $acronym
     */
    protected $acronym;

    /**
     * @var integer $grade_model_id
     */
    protected $grade_model_id;


    /**
     * Get id
     *
     * @return integer 
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * Set percentage
     *
     * @param string $value
     * @return GradeComponents
     */
    public function set_percentage($value)
    {
        $this->percentage = $value;
        return $this;
    }

    /**
     * Get percentage
     *
     * @return string 
     */
    public function get_percentage()
    {
        return $this->percentage;
    }

    /**
     * Set title
     *
     * @param string $value
     * @return GradeComponents
     */
    public function set_title($value)
    {
        $this->title = $value;
        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function get_title()
    {
        return $this->title;
    }

    /**
     * Set acronym
     *
     * @param string $value
     * @return GradeComponents
     */
    public function set_acronym($value)
    {
        $this->acronym = $value;
        return $this;
    }

    /**
     * Get acronym
     *
     * @return string 
     */
    public function get_acronym()
    {
        return $this->acronym;
    }

    /**
     * Set grade_model_id
     *
     * @param integer $value
     * @return GradeComponents
     */
    public function set_grade_model_id($value)
    {
        $this->grade_model_id = $value;
        return $this;
    }

    /**
     * Get grade_model_id
     *
     * @return integer 
     */
    public function get_grade_model_id()
    {
        return $this->grade_model_id;
    }
}