<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class GroupRelGroup extends \Entity
{
    /**
     * @return \Entity\Repository\GroupRelGroupRepository
     */
     public static function repository(){
        return \Entity\Repository\GroupRelGroupRepository::instance();
    }

    /**
     * @return \Entity\GroupRelGroup
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var integer $group_id
     */
    protected $group_id;

    /**
     * @var integer $subgroup_id
     */
    protected $subgroup_id;

    /**
     * @var integer $relation_type
     */
    protected $relation_type;


    /**
     * Get id
     *
     * @return integer 
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * Set group_id
     *
     * @param integer $value
     * @return GroupRelGroup
     */
    public function set_group_id($value)
    {
        $this->group_id = $value;
        return $this;
    }

    /**
     * Get group_id
     *
     * @return integer 
     */
    public function get_group_id()
    {
        return $this->group_id;
    }

    /**
     * Set subgroup_id
     *
     * @param integer $value
     * @return GroupRelGroup
     */
    public function set_subgroup_id($value)
    {
        $this->subgroup_id = $value;
        return $this;
    }

    /**
     * Get subgroup_id
     *
     * @return integer 
     */
    public function get_subgroup_id()
    {
        return $this->subgroup_id;
    }

    /**
     * Set relation_type
     *
     * @param integer $value
     * @return GroupRelGroup
     */
    public function set_relation_type($value)
    {
        $this->relation_type = $value;
        return $this;
    }

    /**
     * Get relation_type
     *
     * @return integer 
     */
    public function get_relation_type()
    {
        return $this->relation_type;
    }
}