<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class ItemProperty extends \CourseEntity
{
    /**
     * @return \Entity\Repository\ItemPropertyRepository
     */
     public static function repository(){
        return \Entity\Repository\ItemPropertyRepository::instance();
    }

    /**
     * @return \Entity\ItemProperty
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $c_id
     */
    protected $c_id;

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var string $tool
     */
    protected $tool;

    /**
     * @var integer $insert_user_id
     */
    protected $insert_user_id;

    /**
     * @var datetime $insert_date
     */
    protected $insert_date;

    /**
     * @var datetime $lastedit_date
     */
    protected $lastedit_date;

    /**
     * @var integer $ref
     */
    protected $ref;

    /**
     * @var string $lastedit_type
     */
    protected $lastedit_type;

    /**
     * @var integer $lastedit_user_id
     */
    protected $lastedit_user_id;

    /**
     * @var integer $to_group_id
     */
    protected $to_group_id;

    /**
     * @var integer $to_user_id
     */
    protected $to_user_id;

    /**
     * @var boolean $visibility
     */
    protected $visibility;

    /**
     * @var datetime $start_visible
     */
    protected $start_visible;

    /**
     * @var datetime $end_visible
     */
    protected $end_visible;

    /**
     * @var integer $id_session
     */
    protected $id_session;


    /**
     * Set c_id
     *
     * @param integer $value
     * @return ItemProperty
     */
    public function set_c_id($value)
    {
        $this->c_id = $value;
        return $this;
    }

    /**
     * Get c_id
     *
     * @return integer 
     */
    public function get_c_id()
    {
        return $this->c_id;
    }

    /**
     * Set id
     *
     * @param integer $value
     * @return ItemProperty
     */
    public function set_id($value)
    {
        $this->id = $value;
        return $this;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * Set tool
     *
     * @param string $value
     * @return ItemProperty
     */
    public function set_tool($value)
    {
        $this->tool = $value;
        return $this;
    }

    /**
     * Get tool
     *
     * @return string 
     */
    public function get_tool()
    {
        return $this->tool;
    }

    /**
     * Set insert_user_id
     *
     * @param integer $value
     * @return ItemProperty
     */
    public function set_insert_user_id($value)
    {
        $this->insert_user_id = $value;
        return $this;
    }

    /**
     * Get insert_user_id
     *
     * @return integer 
     */
    public function get_insert_user_id()
    {
        return $this->insert_user_id;
    }

    /**
     * Set insert_date
     *
     * @param datetime $value
     * @return ItemProperty
     */
    public function set_insert_date($value)
    {
        $this->insert_date = $value;
        return $this;
    }

    /**
     * Get insert_date
     *
     * @return datetime 
     */
    public function get_insert_date()
    {
        return $this->insert_date;
    }

    /**
     * Set lastedit_date
     *
     * @param datetime $value
     * @return ItemProperty
     */
    public function set_lastedit_date($value)
    {
        $this->lastedit_date = $value;
        return $this;
    }

    /**
     * Get lastedit_date
     *
     * @return datetime 
     */
    public function get_lastedit_date()
    {
        return $this->lastedit_date;
    }

    /**
     * Set ref
     *
     * @param integer $value
     * @return ItemProperty
     */
    public function set_ref($value)
    {
        $this->ref = $value;
        return $this;
    }

    /**
     * Get ref
     *
     * @return integer 
     */
    public function get_ref()
    {
        return $this->ref;
    }

    /**
     * Set lastedit_type
     *
     * @param string $value
     * @return ItemProperty
     */
    public function set_lastedit_type($value)
    {
        $this->lastedit_type = $value;
        return $this;
    }

    /**
     * Get lastedit_type
     *
     * @return string 
     */
    public function get_lastedit_type()
    {
        return $this->lastedit_type;
    }

    /**
     * Set lastedit_user_id
     *
     * @param integer $value
     * @return ItemProperty
     */
    public function set_lastedit_user_id($value)
    {
        $this->lastedit_user_id = $value;
        return $this;
    }

    /**
     * Get lastedit_user_id
     *
     * @return integer 
     */
    public function get_lastedit_user_id()
    {
        return $this->lastedit_user_id;
    }

    /**
     * Set to_group_id
     *
     * @param integer $value
     * @return ItemProperty
     */
    public function set_to_group_id($value)
    {
        $this->to_group_id = $value;
        return $this;
    }

    /**
     * Get to_group_id
     *
     * @return integer 
     */
    public function get_to_group_id()
    {
        return $this->to_group_id;
    }

    /**
     * Set to_user_id
     *
     * @param integer $value
     * @return ItemProperty
     */
    public function set_to_user_id($value)
    {
        $this->to_user_id = $value;
        return $this;
    }

    /**
     * Get to_user_id
     *
     * @return integer 
     */
    public function get_to_user_id()
    {
        return $this->to_user_id;
    }

    /**
     * Set visibility
     *
     * @param boolean $value
     * @return ItemProperty
     */
    public function set_visibility($value)
    {
        $this->visibility = $value;
        return $this;
    }

    /**
     * Get visibility
     *
     * @return boolean 
     */
    public function get_visibility()
    {
        return $this->visibility;
    }

    /**
     * Set start_visible
     *
     * @param datetime $value
     * @return ItemProperty
     */
    public function set_start_visible($value)
    {
        $this->start_visible = $value;
        return $this;
    }

    /**
     * Get start_visible
     *
     * @return datetime 
     */
    public function get_start_visible()
    {
        return $this->start_visible;
    }

    /**
     * Set end_visible
     *
     * @param datetime $value
     * @return ItemProperty
     */
    public function set_end_visible($value)
    {
        $this->end_visible = $value;
        return $this;
    }

    /**
     * Get end_visible
     *
     * @return datetime 
     */
    public function get_end_visible()
    {
        return $this->end_visible;
    }

    /**
     * Set id_session
     *
     * @param integer $value
     * @return ItemProperty
     */
    public function set_id_session($value)
    {
        $this->id_session = $value;
        return $this;
    }

    /**
     * Get id_session
     *
     * @return integer 
     */
    public function get_id_session()
    {
        return $this->id_session;
    }
}