<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class LpView extends \CourseEntity
{
    /**
     * @return \Entity\Repository\LpViewRepository
     */
     public static function repository(){
        return \Entity\Repository\LpViewRepository::instance();
    }

    /**
     * @return \Entity\LpView
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $c_id
     */
    protected $c_id;

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var integer $lp_id
     */
    protected $lp_id;

    /**
     * @var integer $user_id
     */
    protected $user_id;

    /**
     * @var integer $view_count
     */
    protected $view_count;

    /**
     * @var integer $last_item
     */
    protected $last_item;

    /**
     * @var integer $progress
     */
    protected $progress;

    /**
     * @var integer $session_id
     */
    protected $session_id;


    /**
     * Set c_id
     *
     * @param integer $value
     * @return LpView
     */
    public function set_c_id($value)
    {
        $this->c_id = $value;
        return $this;
    }

    /**
     * Get c_id
     *
     * @return integer 
     */
    public function get_c_id()
    {
        return $this->c_id;
    }

    /**
     * Set id
     *
     * @param integer $value
     * @return LpView
     */
    public function set_id($value)
    {
        $this->id = $value;
        return $this;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * Set lp_id
     *
     * @param integer $value
     * @return LpView
     */
    public function set_lp_id($value)
    {
        $this->lp_id = $value;
        return $this;
    }

    /**
     * Get lp_id
     *
     * @return integer 
     */
    public function get_lp_id()
    {
        return $this->lp_id;
    }

    /**
     * Set user_id
     *
     * @param integer $value
     * @return LpView
     */
    public function set_user_id($value)
    {
        $this->user_id = $value;
        return $this;
    }

    /**
     * Get user_id
     *
     * @return integer 
     */
    public function get_user_id()
    {
        return $this->user_id;
    }

    /**
     * Set view_count
     *
     * @param integer $value
     * @return LpView
     */
    public function set_view_count($value)
    {
        $this->view_count = $value;
        return $this;
    }

    /**
     * Get view_count
     *
     * @return integer 
     */
    public function get_view_count()
    {
        return $this->view_count;
    }

    /**
     * Set last_item
     *
     * @param integer $value
     * @return LpView
     */
    public function set_last_item($value)
    {
        $this->last_item = $value;
        return $this;
    }

    /**
     * Get last_item
     *
     * @return integer 
     */
    public function get_last_item()
    {
        return $this->last_item;
    }

    /**
     * Set progress
     *
     * @param integer $value
     * @return LpView
     */
    public function set_progress($value)
    {
        $this->progress = $value;
        return $this;
    }

    /**
     * Get progress
     *
     * @return integer 
     */
    public function get_progress()
    {
        return $this->progress;
    }

    /**
     * Set session_id
     *
     * @param integer $value
     * @return LpView
     */
    public function set_session_id($value)
    {
        $this->session_id = $value;
        return $this;
    }

    /**
     * Get session_id
     *
     * @return integer 
     */
    public function get_session_id()
    {
        return $this->session_id;
    }
}