<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class Message extends \Entity
{
    /**
     * @return \Entity\Repository\MessageRepository
     */
     public static function repository(){
        return \Entity\Repository\MessageRepository::instance();
    }

    /**
     * @return \Entity\Message
     */
     public static function create(){
        return new self();
    }

    /**
     * @var bigint $id
     */
    protected $id;

    /**
     * @var integer $user_sender_id
     */
    protected $user_sender_id;

    /**
     * @var integer $user_receiver_id
     */
    protected $user_receiver_id;

    /**
     * @var boolean $msg_status
     */
    protected $msg_status;

    /**
     * @var datetime $send_date
     */
    protected $send_date;

    /**
     * @var string $title
     */
    protected $title;

    /**
     * @var text $content
     */
    protected $content;

    /**
     * @var integer $group_id
     */
    protected $group_id;

    /**
     * @var integer $parent_id
     */
    protected $parent_id;

    /**
     * @var datetime $update_date
     */
    protected $update_date;


    /**
     * Get id
     *
     * @return bigint 
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * Set user_sender_id
     *
     * @param integer $value
     * @return Message
     */
    public function set_user_sender_id($value)
    {
        $this->user_sender_id = $value;
        return $this;
    }

    /**
     * Get user_sender_id
     *
     * @return integer 
     */
    public function get_user_sender_id()
    {
        return $this->user_sender_id;
    }

    /**
     * Set user_receiver_id
     *
     * @param integer $value
     * @return Message
     */
    public function set_user_receiver_id($value)
    {
        $this->user_receiver_id = $value;
        return $this;
    }

    /**
     * Get user_receiver_id
     *
     * @return integer 
     */
    public function get_user_receiver_id()
    {
        return $this->user_receiver_id;
    }

    /**
     * Set msg_status
     *
     * @param boolean $value
     * @return Message
     */
    public function set_msg_status($value)
    {
        $this->msg_status = $value;
        return $this;
    }

    /**
     * Get msg_status
     *
     * @return boolean 
     */
    public function get_msg_status()
    {
        return $this->msg_status;
    }

    /**
     * Set send_date
     *
     * @param datetime $value
     * @return Message
     */
    public function set_send_date($value)
    {
        $this->send_date = $value;
        return $this;
    }

    /**
     * Get send_date
     *
     * @return datetime 
     */
    public function get_send_date()
    {
        return $this->send_date;
    }

    /**
     * Set title
     *
     * @param string $value
     * @return Message
     */
    public function set_title($value)
    {
        $this->title = $value;
        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function get_title()
    {
        return $this->title;
    }

    /**
     * Set content
     *
     * @param text $value
     * @return Message
     */
    public function set_content($value)
    {
        $this->content = $value;
        return $this;
    }

    /**
     * Get content
     *
     * @return text 
     */
    public function get_content()
    {
        return $this->content;
    }

    /**
     * Set group_id
     *
     * @param integer $value
     * @return Message
     */
    public function set_group_id($value)
    {
        $this->group_id = $value;
        return $this;
    }

    /**
     * Get group_id
     *
     * @return integer 
     */
    public function get_group_id()
    {
        return $this->group_id;
    }

    /**
     * Set parent_id
     *
     * @param integer $value
     * @return Message
     */
    public function set_parent_id($value)
    {
        $this->parent_id = $value;
        return $this;
    }

    /**
     * Get parent_id
     *
     * @return integer 
     */
    public function get_parent_id()
    {
        return $this->parent_id;
    }

    /**
     * Set update_date
     *
     * @param datetime $value
     * @return Message
     */
    public function set_update_date($value)
    {
        $this->update_date = $value;
        return $this;
    }

    /**
     * Get update_date
     *
     * @return datetime 
     */
    public function get_update_date()
    {
        return $this->update_date;
    }
}