<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class Notebook extends \CourseEntity
{
    /**
     * @return \Entity\Repository\NotebookRepository
     */
     public static function repository(){
        return \Entity\Repository\NotebookRepository::instance();
    }

    /**
     * @return \Entity\Notebook
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $c_id
     */
    protected $c_id;

    /**
     * @var integer $notebook_id
     */
    protected $notebook_id;

    /**
     * @var integer $user_id
     */
    protected $user_id;

    /**
     * @var string $course
     */
    protected $course;

    /**
     * @var integer $session_id
     */
    protected $session_id;

    /**
     * @var string $title
     */
    protected $title;

    /**
     * @var text $description
     */
    protected $description;

    /**
     * @var datetime $creation_date
     */
    protected $creation_date;

    /**
     * @var datetime $update_date
     */
    protected $update_date;

    /**
     * @var integer $status
     */
    protected $status;


    /**
     * Set c_id
     *
     * @param integer $value
     * @return Notebook
     */
    public function set_c_id($value)
    {
        $this->c_id = $value;
        return $this;
    }

    /**
     * Get c_id
     *
     * @return integer 
     */
    public function get_c_id()
    {
        return $this->c_id;
    }

    /**
     * Set notebook_id
     *
     * @param integer $value
     * @return Notebook
     */
    public function set_notebook_id($value)
    {
        $this->notebook_id = $value;
        return $this;
    }

    /**
     * Get notebook_id
     *
     * @return integer 
     */
    public function get_notebook_id()
    {
        return $this->notebook_id;
    }

    /**
     * Set user_id
     *
     * @param integer $value
     * @return Notebook
     */
    public function set_user_id($value)
    {
        $this->user_id = $value;
        return $this;
    }

    /**
     * Get user_id
     *
     * @return integer 
     */
    public function get_user_id()
    {
        return $this->user_id;
    }

    /**
     * Set course
     *
     * @param string $value
     * @return Notebook
     */
    public function set_course($value)
    {
        $this->course = $value;
        return $this;
    }

    /**
     * Get course
     *
     * @return string 
     */
    public function get_course()
    {
        return $this->course;
    }

    /**
     * Set session_id
     *
     * @param integer $value
     * @return Notebook
     */
    public function set_session_id($value)
    {
        $this->session_id = $value;
        return $this;
    }

    /**
     * Get session_id
     *
     * @return integer 
     */
    public function get_session_id()
    {
        return $this->session_id;
    }

    /**
     * Set title
     *
     * @param string $value
     * @return Notebook
     */
    public function set_title($value)
    {
        $this->title = $value;
        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function get_title()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param text $value
     * @return Notebook
     */
    public function set_description($value)
    {
        $this->description = $value;
        return $this;
    }

    /**
     * Get description
     *
     * @return text 
     */
    public function get_description()
    {
        return $this->description;
    }

    /**
     * Set creation_date
     *
     * @param datetime $value
     * @return Notebook
     */
    public function set_creation_date($value)
    {
        $this->creation_date = $value;
        return $this;
    }

    /**
     * Get creation_date
     *
     * @return datetime 
     */
    public function get_creation_date()
    {
        return $this->creation_date;
    }

    /**
     * Set update_date
     *
     * @param datetime $value
     * @return Notebook
     */
    public function set_update_date($value)
    {
        $this->update_date = $value;
        return $this;
    }

    /**
     * Get update_date
     *
     * @return datetime 
     */
    public function get_update_date()
    {
        return $this->update_date;
    }

    /**
     * Set status
     *
     * @param integer $value
     * @return Notebook
     */
    public function set_status($value)
    {
        $this->status = $value;
        return $this;
    }

    /**
     * Get status
     *
     * @return integer 
     */
    public function get_status()
    {
        return $this->status;
    }
}