<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class Notification extends \Entity
{
    /**
     * @return \Entity\Repository\NotificationRepository
     */
     public static function repository(){
        return \Entity\Repository\NotificationRepository::instance();
    }

    /**
     * @return \Entity\Notification
     */
     public static function create(){
        return new self();
    }

    /**
     * @var bigint $id
     */
    protected $id;

    /**
     * @var integer $dest_user_id
     */
    protected $dest_user_id;

    /**
     * @var string $dest_mail
     */
    protected $dest_mail;

    /**
     * @var string $title
     */
    protected $title;

    /**
     * @var string $content
     */
    protected $content;

    /**
     * @var smallint $send_freq
     */
    protected $send_freq;

    /**
     * @var datetime $created_at
     */
    protected $created_at;

    /**
     * @var datetime $sent_at
     */
    protected $sent_at;


    /**
     * Get id
     *
     * @return bigint 
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * Set dest_user_id
     *
     * @param integer $value
     * @return Notification
     */
    public function set_dest_user_id($value)
    {
        $this->dest_user_id = $value;
        return $this;
    }

    /**
     * Get dest_user_id
     *
     * @return integer 
     */
    public function get_dest_user_id()
    {
        return $this->dest_user_id;
    }

    /**
     * Set dest_mail
     *
     * @param string $value
     * @return Notification
     */
    public function set_dest_mail($value)
    {
        $this->dest_mail = $value;
        return $this;
    }

    /**
     * Get dest_mail
     *
     * @return string 
     */
    public function get_dest_mail()
    {
        return $this->dest_mail;
    }

    /**
     * Set title
     *
     * @param string $value
     * @return Notification
     */
    public function set_title($value)
    {
        $this->title = $value;
        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function get_title()
    {
        return $this->title;
    }

    /**
     * Set content
     *
     * @param string $value
     * @return Notification
     */
    public function set_content($value)
    {
        $this->content = $value;
        return $this;
    }

    /**
     * Get content
     *
     * @return string 
     */
    public function get_content()
    {
        return $this->content;
    }

    /**
     * Set send_freq
     *
     * @param smallint $value
     * @return Notification
     */
    public function set_send_freq($value)
    {
        $this->send_freq = $value;
        return $this;
    }

    /**
     * Get send_freq
     *
     * @return smallint 
     */
    public function get_send_freq()
    {
        return $this->send_freq;
    }

    /**
     * Set created_at
     *
     * @param datetime $value
     * @return Notification
     */
    public function set_created_at($value)
    {
        $this->created_at = $value;
        return $this;
    }

    /**
     * Get created_at
     *
     * @return datetime 
     */
    public function get_created_at()
    {
        return $this->created_at;
    }

    /**
     * Set sent_at
     *
     * @param datetime $value
     * @return Notification
     */
    public function set_sent_at($value)
    {
        $this->sent_at = $value;
        return $this;
    }

    /**
     * Get sent_at
     *
     * @return datetime 
     */
    public function get_sent_at()
    {
        return $this->sent_at;
    }
}