<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class PermissionUser extends \CourseEntity
{
    /**
     * @return \Entity\Repository\PermissionUserRepository
     */
     public static function repository(){
        return \Entity\Repository\PermissionUserRepository::instance();
    }

    /**
     * @return \Entity\PermissionUser
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $c_id
     */
    protected $c_id;

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var integer $user_id
     */
    protected $user_id;

    /**
     * @var string $tool
     */
    protected $tool;

    /**
     * @var string $action
     */
    protected $action;


    /**
     * Set c_id
     *
     * @param integer $value
     * @return PermissionUser
     */
    public function set_c_id($value)
    {
        $this->c_id = $value;
        return $this;
    }

    /**
     * Get c_id
     *
     * @return integer 
     */
    public function get_c_id()
    {
        return $this->c_id;
    }

    /**
     * Set id
     *
     * @param integer $value
     * @return PermissionUser
     */
    public function set_id($value)
    {
        $this->id = $value;
        return $this;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * Set user_id
     *
     * @param integer $value
     * @return PermissionUser
     */
    public function set_user_id($value)
    {
        $this->user_id = $value;
        return $this;
    }

    /**
     * Get user_id
     *
     * @return integer 
     */
    public function get_user_id()
    {
        return $this->user_id;
    }

    /**
     * Set tool
     *
     * @param string $value
     * @return PermissionUser
     */
    public function set_tool($value)
    {
        $this->tool = $value;
        return $this;
    }

    /**
     * Get tool
     *
     * @return string 
     */
    public function get_tool()
    {
        return $this->tool;
    }

    /**
     * Set action
     *
     * @param string $value
     * @return PermissionUser
     */
    public function set_action($value)
    {
        $this->action = $value;
        return $this;
    }

    /**
     * Get action
     *
     * @return string 
     */
    public function get_action()
    {
        return $this->action;
    }
}