<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class PhpSession extends \Entity
{
    /**
     * @return \Entity\Repository\PhpSessionRepository
     */
     public static function repository(){
        return \Entity\Repository\PhpSessionRepository::instance();
    }

    /**
     * @return \Entity\PhpSession
     */
     public static function create(){
        return new self();
    }

    /**
     * @var string $session_id
     */
    protected $session_id;

    /**
     * @var string $session_name
     */
    protected $session_name;

    /**
     * @var integer $session_time
     */
    protected $session_time;

    /**
     * @var integer $session_start
     */
    protected $session_start;

    /**
     * @var text $session_value
     */
    protected $session_value;


    /**
     * Get session_id
     *
     * @return string 
     */
    public function get_session_id()
    {
        return $this->session_id;
    }

    /**
     * Set session_name
     *
     * @param string $value
     * @return PhpSession
     */
    public function set_session_name($value)
    {
        $this->session_name = $value;
        return $this;
    }

    /**
     * Get session_name
     *
     * @return string 
     */
    public function get_session_name()
    {
        return $this->session_name;
    }

    /**
     * Set session_time
     *
     * @param integer $value
     * @return PhpSession
     */
    public function set_session_time($value)
    {
        $this->session_time = $value;
        return $this;
    }

    /**
     * Get session_time
     *
     * @return integer 
     */
    public function get_session_time()
    {
        return $this->session_time;
    }

    /**
     * Set session_start
     *
     * @param integer $value
     * @return PhpSession
     */
    public function set_session_start($value)
    {
        $this->session_start = $value;
        return $this;
    }

    /**
     * Get session_start
     *
     * @return integer 
     */
    public function get_session_start()
    {
        return $this->session_start;
    }

    /**
     * Set session_value
     *
     * @param text $value
     * @return PhpSession
     */
    public function set_session_value($value)
    {
        $this->session_value = $value;
        return $this;
    }

    /**
     * Get session_value
     *
     * @return text 
     */
    public function get_session_value()
    {
        return $this->session_value;
    }
}