<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class Resource extends \CourseEntity
{
    /**
     * @return \Entity\Repository\ResourceRepository
     */
     public static function repository(){
        return \Entity\Repository\ResourceRepository::instance();
    }

    /**
     * @return \Entity\Resource
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $c_id
     */
    protected $c_id;

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var string $source_type
     */
    protected $source_type;

    /**
     * @var integer $source_id
     */
    protected $source_id;

    /**
     * @var string $resource_type
     */
    protected $resource_type;

    /**
     * @var integer $resource_id
     */
    protected $resource_id;


    /**
     * Set c_id
     *
     * @param integer $value
     * @return Resource
     */
    public function set_c_id($value)
    {
        $this->c_id = $value;
        return $this;
    }

    /**
     * Get c_id
     *
     * @return integer 
     */
    public function get_c_id()
    {
        return $this->c_id;
    }

    /**
     * Set id
     *
     * @param integer $value
     * @return Resource
     */
    public function set_id($value)
    {
        $this->id = $value;
        return $this;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * Set source_type
     *
     * @param string $value
     * @return Resource
     */
    public function set_source_type($value)
    {
        $this->source_type = $value;
        return $this;
    }

    /**
     * Get source_type
     *
     * @return string 
     */
    public function get_source_type()
    {
        return $this->source_type;
    }

    /**
     * Set source_id
     *
     * @param integer $value
     * @return Resource
     */
    public function set_source_id($value)
    {
        $this->source_id = $value;
        return $this;
    }

    /**
     * Get source_id
     *
     * @return integer 
     */
    public function get_source_id()
    {
        return $this->source_id;
    }

    /**
     * Set resource_type
     *
     * @param string $value
     * @return Resource
     */
    public function set_resource_type($value)
    {
        $this->resource_type = $value;
        return $this;
    }

    /**
     * Get resource_type
     *
     * @return string 
     */
    public function get_resource_type()
    {
        return $this->resource_type;
    }

    /**
     * Set resource_id
     *
     * @param integer $value
     * @return Resource
     */
    public function set_resource_id($value)
    {
        $this->resource_id = $value;
        return $this;
    }

    /**
     * Get resource_id
     *
     * @return integer 
     */
    public function get_resource_id()
    {
        return $this->resource_id;
    }
}