<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class SessionRelUser extends \Entity
{
    /**
     * @return \Entity\Repository\SessionRelUserRepository
     */
     public static function repository(){
        return \Entity\Repository\SessionRelUserRepository::instance();
    }

    /**
     * @return \Entity\SessionRelUser
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $id_session
     */
    protected $id_session;

    /**
     * @var integer $id_user
     */
    protected $id_user;

    /**
     * @var integer $relation_type
     */
    protected $relation_type;


    /**
     * Set id_session
     *
     * @param integer $value
     * @return SessionRelUser
     */
    public function set_id_session($value)
    {
        $this->id_session = $value;
        return $this;
    }

    /**
     * Get id_session
     *
     * @return integer 
     */
    public function get_id_session()
    {
        return $this->id_session;
    }

    /**
     * Set id_user
     *
     * @param integer $value
     * @return SessionRelUser
     */
    public function set_id_user($value)
    {
        $this->id_user = $value;
        return $this;
    }

    /**
     * Get id_user
     *
     * @return integer 
     */
    public function get_id_user()
    {
        return $this->id_user;
    }

    /**
     * Set relation_type
     *
     * @param integer $value
     * @return SessionRelUser
     */
    public function set_relation_type($value)
    {
        $this->relation_type = $value;
        return $this;
    }

    /**
     * Get relation_type
     *
     * @return integer 
     */
    public function get_relation_type()
    {
        return $this->relation_type;
    }
}