<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class SkillRelGradebook extends \Entity
{
    /**
     * @return \Entity\Repository\SkillRelGradebookRepository
     */
     public static function repository(){
        return \Entity\Repository\SkillRelGradebookRepository::instance();
    }

    /**
     * @return \Entity\SkillRelGradebook
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var integer $gradebook_id
     */
    protected $gradebook_id;

    /**
     * @var integer $skill_id
     */
    protected $skill_id;

    /**
     * @var string $type
     */
    protected $type;


    /**
     * Get id
     *
     * @return integer 
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * Set gradebook_id
     *
     * @param integer $value
     * @return SkillRelGradebook
     */
    public function set_gradebook_id($value)
    {
        $this->gradebook_id = $value;
        return $this;
    }

    /**
     * Get gradebook_id
     *
     * @return integer 
     */
    public function get_gradebook_id()
    {
        return $this->gradebook_id;
    }

    /**
     * Set skill_id
     *
     * @param integer $value
     * @return SkillRelGradebook
     */
    public function set_skill_id($value)
    {
        $this->skill_id = $value;
        return $this;
    }

    /**
     * Get skill_id
     *
     * @return integer 
     */
    public function get_skill_id()
    {
        return $this->skill_id;
    }

    /**
     * Set type
     *
     * @param string $value
     * @return SkillRelGradebook
     */
    public function set_type($value)
    {
        $this->type = $value;
        return $this;
    }

    /**
     * Get type
     *
     * @return string 
     */
    public function get_type()
    {
        return $this->type;
    }
}