<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class SkillRelUser extends \Entity
{
    /**
     * @return \Entity\Repository\SkillRelUserRepository
     */
     public static function repository(){
        return \Entity\Repository\SkillRelUserRepository::instance();
    }

    /**
     * @return \Entity\SkillRelUser
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var integer $user_id
     */
    protected $user_id;

    /**
     * @var integer $skill_id
     */
    protected $skill_id;

    /**
     * @var datetime $acquired_skill_at
     */
    protected $acquired_skill_at;

    /**
     * @var integer $assigned_by
     */
    protected $assigned_by;


    /**
     * Get id
     *
     * @return integer 
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * Set user_id
     *
     * @param integer $value
     * @return SkillRelUser
     */
    public function set_user_id($value)
    {
        $this->user_id = $value;
        return $this;
    }

    /**
     * Get user_id
     *
     * @return integer 
     */
    public function get_user_id()
    {
        return $this->user_id;
    }

    /**
     * Set skill_id
     *
     * @param integer $value
     * @return SkillRelUser
     */
    public function set_skill_id($value)
    {
        $this->skill_id = $value;
        return $this;
    }

    /**
     * Get skill_id
     *
     * @return integer 
     */
    public function get_skill_id()
    {
        return $this->skill_id;
    }

    /**
     * Set acquired_skill_at
     *
     * @param datetime $value
     * @return SkillRelUser
     */
    public function set_acquired_skill_at($value)
    {
        $this->acquired_skill_at = $value;
        return $this;
    }

    /**
     * Get acquired_skill_at
     *
     * @return datetime 
     */
    public function get_acquired_skill_at()
    {
        return $this->acquired_skill_at;
    }

    /**
     * Set assigned_by
     *
     * @param integer $value
     * @return SkillRelUser
     */
    public function set_assigned_by($value)
    {
        $this->assigned_by = $value;
        return $this;
    }

    /**
     * Get assigned_by
     *
     * @return integer 
     */
    public function get_assigned_by()
    {
        return $this->assigned_by;
    }
}