<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class SkillRelProfile extends \Entity
{
    /**
     * @return \Entity\Repository\SkillRelProfileRepository
     */
     public static function repository(){
        return \Entity\Repository\SkillRelProfileRepository::instance();
    }

    /**
     * @return \Entity\SkillRelProfile
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var integer $skill_id
     */
    protected $skill_id;

    /**
     * @var integer $profile_id
     */
    protected $profile_id;


    /**
     * Get id
     *
     * @return integer 
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * Set skill_id
     *
     * @param integer $value
     * @return SkillRelProfile
     */
    public function set_skill_id($value)
    {
        $this->skill_id = $value;
        return $this;
    }

    /**
     * Get skill_id
     *
     * @return integer 
     */
    public function get_skill_id()
    {
        return $this->skill_id;
    }

    /**
     * Set profile_id
     *
     * @param integer $value
     * @return SkillRelProfile
     */
    public function set_profile_id($value)
    {
        $this->profile_id = $value;
        return $this;
    }

    /**
     * Get profile_id
     *
     * @return integer 
     */
    public function get_profile_id()
    {
        return $this->profile_id;
    }
}