<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class StudentPublicationAssignment extends \CourseEntity
{
    /**
     * @return \Entity\Repository\StudentPublicationAssignmentRepository
     */
     public static function repository(){
        return \Entity\Repository\StudentPublicationAssignmentRepository::instance();
    }

    /**
     * @return \Entity\StudentPublicationAssignment
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $c_id
     */
    protected $c_id;

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var datetime $expires_on
     */
    protected $expires_on;

    /**
     * @var datetime $ends_on
     */
    protected $ends_on;

    /**
     * @var boolean $add_to_calendar
     */
    protected $add_to_calendar;

    /**
     * @var boolean $enable_qualification
     */
    protected $enable_qualification;

    /**
     * @var integer $publication_id
     */
    protected $publication_id;


    /**
     * Set c_id
     *
     * @param integer $value
     * @return StudentPublicationAssignment
     */
    public function set_c_id($value)
    {
        $this->c_id = $value;
        return $this;
    }

    /**
     * Get c_id
     *
     * @return integer 
     */
    public function get_c_id()
    {
        return $this->c_id;
    }

    /**
     * Set id
     *
     * @param integer $value
     * @return StudentPublicationAssignment
     */
    public function set_id($value)
    {
        $this->id = $value;
        return $this;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * Set expires_on
     *
     * @param datetime $value
     * @return StudentPublicationAssignment
     */
    public function set_expires_on($value)
    {
        $this->expires_on = $value;
        return $this;
    }

    /**
     * Get expires_on
     *
     * @return datetime 
     */
    public function get_expires_on()
    {
        return $this->expires_on;
    }

    /**
     * Set ends_on
     *
     * @param datetime $value
     * @return StudentPublicationAssignment
     */
    public function set_ends_on($value)
    {
        $this->ends_on = $value;
        return $this;
    }

    /**
     * Get ends_on
     *
     * @return datetime 
     */
    public function get_ends_on()
    {
        return $this->ends_on;
    }

    /**
     * Set add_to_calendar
     *
     * @param boolean $value
     * @return StudentPublicationAssignment
     */
    public function set_add_to_calendar($value)
    {
        $this->add_to_calendar = $value;
        return $this;
    }

    /**
     * Get add_to_calendar
     *
     * @return boolean 
     */
    public function get_add_to_calendar()
    {
        return $this->add_to_calendar;
    }

    /**
     * Set enable_qualification
     *
     * @param boolean $value
     * @return StudentPublicationAssignment
     */
    public function set_enable_qualification($value)
    {
        $this->enable_qualification = $value;
        return $this;
    }

    /**
     * Get enable_qualification
     *
     * @return boolean 
     */
    public function get_enable_qualification()
    {
        return $this->enable_qualification;
    }

    /**
     * Set publication_id
     *
     * @param integer $value
     * @return StudentPublicationAssignment
     */
    public function set_publication_id($value)
    {
        $this->publication_id = $value;
        return $this;
    }

    /**
     * Get publication_id
     *
     * @return integer 
     */
    public function get_publication_id()
    {
        return $this->publication_id;
    }
}