<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class SurveyGroup extends \CourseEntity
{
    /**
     * @return \Entity\Repository\SurveyGroupRepository
     */
     public static function repository(){
        return \Entity\Repository\SurveyGroupRepository::instance();
    }

    /**
     * @return \Entity\SurveyGroup
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $c_id
     */
    protected $c_id;

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var string $name
     */
    protected $name;

    /**
     * @var string $description
     */
    protected $description;

    /**
     * @var integer $survey_id
     */
    protected $survey_id;


    /**
     * Set c_id
     *
     * @param integer $value
     * @return SurveyGroup
     */
    public function set_c_id($value)
    {
        $this->c_id = $value;
        return $this;
    }

    /**
     * Get c_id
     *
     * @return integer 
     */
    public function get_c_id()
    {
        return $this->c_id;
    }

    /**
     * Set id
     *
     * @param integer $value
     * @return SurveyGroup
     */
    public function set_id($value)
    {
        $this->id = $value;
        return $this;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $value
     * @return SurveyGroup
     */
    public function set_name($value)
    {
        $this->name = $value;
        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function get_name()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $value
     * @return SurveyGroup
     */
    public function set_description($value)
    {
        $this->description = $value;
        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function get_description()
    {
        return $this->description;
    }

    /**
     * Set survey_id
     *
     * @param integer $value
     * @return SurveyGroup
     */
    public function set_survey_id($value)
    {
        $this->survey_id = $value;
        return $this;
    }

    /**
     * Get survey_id
     *
     * @return integer 
     */
    public function get_survey_id()
    {
        return $this->survey_id;
    }
}