<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class SurveyQuestionOption extends \CourseEntity
{
    /**
     * @return \Entity\Repository\SurveyQuestionOptionRepository
     */
     public static function repository(){
        return \Entity\Repository\SurveyQuestionOptionRepository::instance();
    }

    /**
     * @return \Entity\SurveyQuestionOption
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $c_id
     */
    protected $c_id;

    /**
     * @var integer $question_option_id
     */
    protected $question_option_id;

    /**
     * @var integer $question_id
     */
    protected $question_id;

    /**
     * @var integer $survey_id
     */
    protected $survey_id;

    /**
     * @var text $option_text
     */
    protected $option_text;

    /**
     * @var integer $sort
     */
    protected $sort;

    /**
     * @var integer $value
     */
    protected $value;


    /**
     * Set c_id
     *
     * @param integer $value
     * @return SurveyQuestionOption
     */
    public function set_c_id($value)
    {
        $this->c_id = $value;
        return $this;
    }

    /**
     * Get c_id
     *
     * @return integer 
     */
    public function get_c_id()
    {
        return $this->c_id;
    }

    /**
     * Set question_option_id
     *
     * @param integer $value
     * @return SurveyQuestionOption
     */
    public function set_question_option_id($value)
    {
        $this->question_option_id = $value;
        return $this;
    }

    /**
     * Get question_option_id
     *
     * @return integer 
     */
    public function get_question_option_id()
    {
        return $this->question_option_id;
    }

    /**
     * Set question_id
     *
     * @param integer $value
     * @return SurveyQuestionOption
     */
    public function set_question_id($value)
    {
        $this->question_id = $value;
        return $this;
    }

    /**
     * Get question_id
     *
     * @return integer 
     */
    public function get_question_id()
    {
        return $this->question_id;
    }

    /**
     * Set survey_id
     *
     * @param integer $value
     * @return SurveyQuestionOption
     */
    public function set_survey_id($value)
    {
        $this->survey_id = $value;
        return $this;
    }

    /**
     * Get survey_id
     *
     * @return integer 
     */
    public function get_survey_id()
    {
        return $this->survey_id;
    }

    /**
     * Set option_text
     *
     * @param text $value
     * @return SurveyQuestionOption
     */
    public function set_option_text($value)
    {
        $this->option_text = $value;
        return $this;
    }

    /**
     * Get option_text
     *
     * @return text 
     */
    public function get_option_text()
    {
        return $this->option_text;
    }

    /**
     * Set sort
     *
     * @param integer $value
     * @return SurveyQuestionOption
     */
    public function set_sort($value)
    {
        $this->sort = $value;
        return $this;
    }

    /**
     * Get sort
     *
     * @return integer 
     */
    public function get_sort()
    {
        return $this->sort;
    }

    /**
     * Set value
     *
     * @param integer $value
     * @return SurveyQuestionOption
     */
    public function set_value($value)
    {
        $this->value = $value;
        return $this;
    }

    /**
     * Get value
     *
     * @return integer 
     */
    public function get_value()
    {
        return $this->value;
    }
}