<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class TrackEAttemptCoeff extends \Entity
{
    /**
     * @return \Entity\Repository\TrackEAttemptCoeffRepository
     */
     public static function repository(){
        return \Entity\Repository\TrackEAttemptCoeffRepository::instance();
    }

    /**
     * @return \Entity\TrackEAttemptCoeff
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var integer $attempt_id
     */
    protected $attempt_id;

    /**
     * @var float $marks_coeff
     */
    protected $marks_coeff;


    /**
     * Get id
     *
     * @return integer 
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * Set attempt_id
     *
     * @param integer $value
     * @return TrackEAttemptCoeff
     */
    public function set_attempt_id($value)
    {
        $this->attempt_id = $value;
        return $this;
    }

    /**
     * Get attempt_id
     *
     * @return integer 
     */
    public function get_attempt_id()
    {
        return $this->attempt_id;
    }

    /**
     * Set marks_coeff
     *
     * @param float $value
     * @return TrackEAttemptCoeff
     */
    public function set_marks_coeff($value)
    {
        $this->marks_coeff = $value;
        return $this;
    }

    /**
     * Get marks_coeff
     *
     * @return float 
     */
    public function get_marks_coeff()
    {
        return $this->marks_coeff;
    }
}