<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class TrackEDownloads extends \Entity
{
    /**
     * @return \Entity\Repository\TrackEDownloadsRepository
     */
     public static function repository(){
        return \Entity\Repository\TrackEDownloadsRepository::instance();
    }

    /**
     * @return \Entity\TrackEDownloads
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $down_id
     */
    protected $down_id;

    /**
     * @var integer $down_user_id
     */
    protected $down_user_id;

    /**
     * @var datetime $down_date
     */
    protected $down_date;

    /**
     * @var string $down_cours_id
     */
    protected $down_cours_id;

    /**
     * @var string $down_doc_path
     */
    protected $down_doc_path;

    /**
     * @var integer $down_session_id
     */
    protected $down_session_id;


    /**
     * Get down_id
     *
     * @return integer 
     */
    public function get_down_id()
    {
        return $this->down_id;
    }

    /**
     * Set down_user_id
     *
     * @param integer $value
     * @return TrackEDownloads
     */
    public function set_down_user_id($value)
    {
        $this->down_user_id = $value;
        return $this;
    }

    /**
     * Get down_user_id
     *
     * @return integer 
     */
    public function get_down_user_id()
    {
        return $this->down_user_id;
    }

    /**
     * Set down_date
     *
     * @param datetime $value
     * @return TrackEDownloads
     */
    public function set_down_date($value)
    {
        $this->down_date = $value;
        return $this;
    }

    /**
     * Get down_date
     *
     * @return datetime 
     */
    public function get_down_date()
    {
        return $this->down_date;
    }

    /**
     * Set down_cours_id
     *
     * @param string $value
     * @return TrackEDownloads
     */
    public function set_down_cours_id($value)
    {
        $this->down_cours_id = $value;
        return $this;
    }

    /**
     * Get down_cours_id
     *
     * @return string 
     */
    public function get_down_cours_id()
    {
        return $this->down_cours_id;
    }

    /**
     * Set down_doc_path
     *
     * @param string $value
     * @return TrackEDownloads
     */
    public function set_down_doc_path($value)
    {
        $this->down_doc_path = $value;
        return $this;
    }

    /**
     * Get down_doc_path
     *
     * @return string 
     */
    public function get_down_doc_path()
    {
        return $this->down_doc_path;
    }

    /**
     * Set down_session_id
     *
     * @param integer $value
     * @return TrackEDownloads
     */
    public function set_down_session_id($value)
    {
        $this->down_session_id = $value;
        return $this;
    }

    /**
     * Get down_session_id
     *
     * @return integer 
     */
    public function get_down_session_id()
    {
        return $this->down_session_id;
    }
}