<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class TrackELogin extends \Entity
{
    /**
     * @return \Entity\Repository\TrackELoginRepository
     */
     public static function repository(){
        return \Entity\Repository\TrackELoginRepository::instance();
    }

    /**
     * @return \Entity\TrackELogin
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $login_id
     */
    protected $login_id;

    /**
     * @var integer $login_user_id
     */
    protected $login_user_id;

    /**
     * @var datetime $login_date
     */
    protected $login_date;

    /**
     * @var string $login_ip
     */
    protected $login_ip;

    /**
     * @var datetime $logout_date
     */
    protected $logout_date;


    /**
     * Get login_id
     *
     * @return integer 
     */
    public function get_login_id()
    {
        return $this->login_id;
    }

    /**
     * Set login_user_id
     *
     * @param integer $value
     * @return TrackELogin
     */
    public function set_login_user_id($value)
    {
        $this->login_user_id = $value;
        return $this;
    }

    /**
     * Get login_user_id
     *
     * @return integer 
     */
    public function get_login_user_id()
    {
        return $this->login_user_id;
    }

    /**
     * Set login_date
     *
     * @param datetime $value
     * @return TrackELogin
     */
    public function set_login_date($value)
    {
        $this->login_date = $value;
        return $this;
    }

    /**
     * Get login_date
     *
     * @return datetime 
     */
    public function get_login_date()
    {
        return $this->login_date;
    }

    /**
     * Set login_ip
     *
     * @param string $value
     * @return TrackELogin
     */
    public function set_login_ip($value)
    {
        $this->login_ip = $value;
        return $this;
    }

    /**
     * Get login_ip
     *
     * @return string 
     */
    public function get_login_ip()
    {
        return $this->login_ip;
    }

    /**
     * Set logout_date
     *
     * @param datetime $value
     * @return TrackELogin
     */
    public function set_logout_date($value)
    {
        $this->logout_date = $value;
        return $this;
    }

    /**
     * Get logout_date
     *
     * @return datetime 
     */
    public function get_logout_date()
    {
        return $this->logout_date;
    }
}