<?php

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @license see /license.txt
 * @author autogenerated
 */
class UserCourseCategory extends \Entity
{
    /**
     * @return \Entity\Repository\UserCourseCategoryRepository
     */
     public static function repository(){
        return \Entity\Repository\UserCourseCategoryRepository::instance();
    }

    /**
     * @return \Entity\UserCourseCategory
     */
     public static function create(){
        return new self();
    }

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var integer $user_id
     */
    protected $user_id;

    /**
     * @var text $title
     */
    protected $title;

    /**
     * @var integer $sort
     */
    protected $sort;


    /**
     * Get id
     *
     * @return integer 
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * Set user_id
     *
     * @param integer $value
     * @return UserCourseCategory
     */
    public function set_user_id($value)
    {
        $this->user_id = $value;
        return $this;
    }

    /**
     * Get user_id
     *
     * @return integer 
     */
    public function get_user_id()
    {
        return $this->user_id;
    }

    /**
     * Set title
     *
     * @param text $value
     * @return UserCourseCategory
     */
    public function set_title($value)
    {
        $this->title = $value;
        return $this;
    }

    /**
     * Get title
     *
     * @return text 
     */
    public function get_title()
    {
        return $this->title;
    }

    /**
     * Set sort
     *
     * @param integer $value
     * @return UserCourseCategory
     */
    public function set_sort($value)
    {
        $this->sort = $value;
        return $this;
    }

    /**
     * Get sort
     *
     * @return integer 
     */
    public function get_sort()
    {
        return $this->sort;
    }
}