<?php
/**
 * Mnogosearch plugin config file
 * @package chamilo.plugin.search
 */
/**
 * Settings
 */
// maximal page number to view
$MAX_NP=1;

// maximum results per page
$MAX_PS=1000;

// (optional) Enable autowild feature for url limits
// 'yes' - default value, can be 'yes' or 'no'
// $auto_wild='yes';

// (optional) Enable language content negotiation
// 'no' - default value, can be 'yes' or 'no'
// $lang_content_negotiation='no';

// (optional) Enable language url translation (file.en.ext -> file)
// 'no' - default value, can be 'yes' or 'no'
// $lang_url_translation='no';

?>
