editAreaLoader.lang["es"]={
new_document: "nuevo documento",
search_button: "buscar y reemplazar",
search_command: "buscar siguiente / abrir ventana de búsqueda",
search: "buscar",
replace: "reemplazar",
replace_command: "reemplazar / abrir ventana de búsqueda",
find_next: "buscar siguiente",
replace_all: "reemplazar todo",
reg_exp: "expresiones regulares",
match_case: "Coincidir mayúsculas y minúsculas",
not_found: "no encontrado.",
occurrence_replaced: "elementos reemplazados.",
search_field_empty: "Campo de búsqueda vacío",
restart_search_at_begin: "Se alcanzó el final del texto. Reiniciar de nuevo.",
move_popup: "mover la ventana de búsqueda",
font_size: "--Tamaño de fuente--",
go_to_line: "ir a la línea",
go_to_line_prompt: "ir a la línea número:",
undo: "deshacer",
redo: "rehacer",
change_smooth_selection: "habilitar/deshabilitar mejoras de visualzación (visualización más elegante pero más carga para la CPU)",
highlight: "activar coloreado sintáctico si/no",
reset_highlight: "reiniciar el coloreado sintáctico (si no hay sincronización con el texto)",
help: "sobre",
save: "guardar",
save_as: "guardar como",
load: "cargar",
line_abbr: "Ln",
char_abbr: "Cr",
position: "Posición",
total: "Total",
close_popup: "cerrar popup",
shortcuts: "Accesos rápidos",
add_tab: "añadir tabulación al texto",
remove_tab: "quitar la tabulación del texto",
about_notice: "Nota: el coloreado sintáctico es sólo para textos cortos",
toggle: "Activar el editor",
accesskey: "Teclas de acceso",
tab: "Tab",
shift: "Mayúsc",
ctrl: "Ctrl",
esc: "Esc",
processing: "Procesando...",
fullscreen: "Pantalla completa"
};
